"""Actual isolated PostgreSQL claim/catalog transactions and scope enforcement."""
from concurrent.futures import ThreadPoolExecutor
from copy import deepcopy
import json
from pathlib import Path
from uuid import uuid4
import psycopg
from psycopg.types.json import Jsonb
import pytest
from tests.test_chat_image_lifecycle_postgres import isolated_db, facts, connection, lifecycle
ROOT=Path(__file__).parents[1]

@pytest.fixture(scope='module',autouse=True)
def source_schema(isolated_db):
    with psycopg.connect(isolated_db) as db:
        db.execute('CREATE EXTENSION "uuid-ossp"')
        db.execute("""
            ALTER TABLE conversations ADD COLUMN last_closed_message_id UUID, ADD COLUMN active_serial_task_id UUID, ADD COLUMN actor_updated_at TIMESTAMPTZ DEFAULT NOW();
            ALTER TABLE tasks ADD COLUMN execution_attempt INTEGER NOT NULL DEFAULT 0, ADD COLUMN lease_expires_at TIMESTAMPTZ,
                ADD COLUMN execution_mode TEXT DEFAULT 'serial', ADD COLUMN queue_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
                ADD COLUMN context_through_message_id UUID, ADD COLUMN terminal_reason TEXT;
            ALTER TABLE messages ADD COLUMN turn_id UUID;
            ALTER TABLE messages ENABLE ROW LEVEL SECURITY; ALTER TABLE messages FORCE ROW LEVEL SECURITY;
            CREATE POLICY test_message_scope ON messages TO everydayai USING (
                org_id IS NOT DISTINCT FROM NULLIF(current_setting('app.org_id',TRUE),'')::UUID
                AND EXISTS(SELECT 1 FROM conversations c WHERE c.id=conversation_id AND c.user_id=NULLIF(current_setting('app.actor_user_id',TRUE),'')::UUID));
            ALTER TABLE conversations ENABLE ROW LEVEL SECURITY; ALTER TABLE conversations FORCE ROW LEVEL SECURITY;
            CREATE POLICY test_conversation_scope ON conversations TO everydayai USING (
                org_id IS NOT DISTINCT FROM NULLIF(current_setting('app.org_id',TRUE),'')::UUID AND user_id=NULLIF(current_setting('app.actor_user_id',TRUE),'')::UUID);
            GRANT TRIGGER ON tasks TO everydayai;
        """)
        old=(ROOT/'migrations/121_conversation_actor_queue.sql').read_text()
        old=old[old.index('CREATE OR REPLACE FUNCTION claim_next_serial_generation_turn('):old.index('CREATE OR REPLACE FUNCTION renew_generation_lease(')]
        db.execute('SET LOCAL ROLE everydayai_owner');db.execute(old);db.execute('RESET ROLE')
        db.execute('GRANT EXECUTE ON FUNCTION claim_next_serial_generation_turn(UUID,INTEGER,INTEGER), claim_branch_generation_turn(UUID,INTEGER,INTEGER) TO everydayai')
        db.execute((ROOT/'migrations/277_chat_image_sources.sql').read_text())
        assert db.execute('SELECT current_user=session_user').fetchone()[0]

@pytest.fixture
def source_facts(facts):
    f=facts;o=f['snapshot']['origin']
    with psycopg.connect(f['dsn']) as db:
        db.execute('DELETE FROM tasks WHERE id=%s',(f['parent'],))
        db.execute("INSERT INTO tasks(id,user_id,conversation_id,type,status,delivery_context,turn_id,input_message_id,base_context_revision,request_params) VALUES (%s,%s,%s,'chat','pending','{\"actor\":true}',%s,%s,0,%s)",
                   (f['parent'],f['user'],o['conversation_id'],o['turn_id'],o['input_message_id'],Jsonb({'_image_sources_v1':{'version':1,'messages':[{'id':'forged'}]}})))
        db.execute("INSERT INTO messages(id,conversation_id,role,content,status) VALUES (%s,%s,'user','[]','completed')",(o['input_message_id'],o['conversation_id']))
    return f

def add_image(f,**changes):
    ident=str(uuid4());o=f['snapshot']['origin']
    values={'conv':o['conversation_id'],'org':None,'role':'user','status':'completed','kind':'conversation','revision':None,
            'content':[{'type':'image','workspace_path':'A.png','name':'A.png'}],**changes}
    with psycopg.connect(f['dsn']) as db:
        db.execute('INSERT INTO messages(id,conversation_id,org_id,role,content,status,message_kind,context_revision) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)',
            (ident,values['conv'],values['org'],values['role'],json.dumps(values['content']),values['status'],values['kind'],values['revision']))
    return ident

def catalog(f):
    with psycopg.connect(f['dsn']) as db:return db.execute("SELECT request_params->'_image_sources_v1' FROM tasks WHERE id=%s",(f['parent'],)).fetchone()[0]

def actor_claim(f,branch=False):
    with connection(f) as db:return db.execute('SELECT claim_branch_generation_turn(%s)' if branch else 'SELECT claim_next_serial_generation_turn(%s)',
        (f['parent'] if branch else f['snapshot']['origin']['conversation_id'],)).fetchone()[0]

@pytest.mark.parametrize('branch',[False,True])
def test_atomic_sources_exclude_unclosed_foreign_internal_and_future_and_reclaim_never_widens(source_facts,branch):
    f=source_facts;good=add_image(f)
    for changes in ({'status':'pending'},{'status':'failed'},{'kind':'tool_internal'},{'org':str(uuid4())},{'conv':str(uuid4())},{'revision':1}):add_image(f,**changes)
    with psycopg.connect(f['dsn']) as db:
        # Inserted forged private JSON is overwritten on first claim.
        db.execute('UPDATE tasks SET execution_mode=%s WHERE id=%s',('branch' if branch else 'serial',f['parent']))
    assert actor_claim(f,branch)['outcome']=='claimed';frozen=deepcopy(catalog(f))
    assert [row['id'] for row in frozen['messages']]==[good]
    add_image(f)
    with psycopg.connect(f['dsn']) as db:
        db.execute("UPDATE messages SET status='completed' WHERE conversation_id=%s AND status='pending'",(f['snapshot']['origin']['conversation_id'],))
        db.execute('UPDATE conversations SET context_revision=8 WHERE id=%s',(f['snapshot']['origin']['conversation_id'],))
        db.execute("UPDATE tasks SET lease_expires_at=NOW()-INTERVAL '1 second' WHERE id=%s",(f['parent'],))
    assert actor_claim(f,branch)['base_context_revision']==0
    assert catalog(f)==frozen

def test_concurrent_claim_once(source_facts):
    f=source_facts;good=add_image(f)
    with ThreadPoolExecutor(max_workers=2) as pool:results=list(pool.map(lambda _:actor_claim(f),range(2)))
    assert sorted(row['outcome'] for row in results)==['busy','claimed']
    assert [row['id'] for row in catalog(f)['messages']]==[good]

def test_catalog_private_updates_cannot_replace_after_claim(source_facts):
    f=source_facts;add_image(f);actor_claim(f)
    for value in ({'version':1,'messages':[]},None):
        with pytest.raises(psycopg.Error,match='IMAGE_SOURCE_CATALOG_IMMUTABLE'):
            with connection(f) as db:db.execute("UPDATE tasks SET request_params=jsonb_set(request_params,'{_image_sources_v1}',%s) WHERE id=%s",(Jsonb(value),f['parent']))
    with connection(f) as db:db.execute("UPDATE tasks SET request_params=request_params || '{\"checkpoint\":true}' WHERE id=%s",(f['parent'],))
    assert len(catalog(f)['messages'])==1

def test_rls_and_public_acl_exclude_other_actor_org(source_facts):
    f=source_facts;add_image(f);actor_claim(f)
    for setting in ('app.actor_user_id','app.org_id'):
        with connection(f) as db:
            db.execute('SELECT set_config(%s,%s,true)',(setting,str(uuid4())))
            assert db.execute('SELECT id FROM messages').fetchall()==[]
            assert db.execute('SELECT id FROM tasks').fetchall()==[]
            with pytest.raises(psycopg.Error,match='ACTOR_CONVERSATION_NOT_FOUND'):db.execute('SELECT claim_next_serial_generation_turn(%s)',(f['snapshot']['origin']['conversation_id'],))
    with psycopg.connect(f['dsn']) as db:assert not db.execute("SELECT has_function_privilege('image_untrusted','freeze_chat_image_sources(tasks,conversations)','EXECUTE')").fetchone()[0]

def test_oversized_sources_freeze_unavailable_without_poisoning_queue(source_facts):
    f=source_facts;add_image(f,content=[{'type':'text','text':'x'*130000},{'type':'image','workspace_path':'A.png'}])
    assert actor_claim(f)['outcome']=='claimed'
    assert catalog(f)['messages']==[]
    assert catalog(f)['unavailable_reason']=='IMAGE_SOURCE_CATALOG_TOO_LARGE_SELECT_EXPLICIT_IMAGES'
    with psycopg.connect(f['dsn']) as db:
        assert db.execute('SELECT status,execution_attempt,execution_token FROM tasks WHERE id=%s',(f['parent'],)).fetchone()[0:2]==('running',1)
        assert db.execute('SELECT active_serial_task_id FROM conversations WHERE id=%s',(f['snapshot']['origin']['conversation_id'],)).fetchone()[0]==__import__('uuid').UUID(f['parent'])

def test_old_checkpoint_without_catalog_cannot_discover_new_legacy_sources(source_facts):
    f=source_facts;add_image(f)
    with psycopg.connect(f['dsn']) as db:db.execute("UPDATE tasks SET request_params='{}',execution_attempt=1,base_context_revision=0 WHERE id=%s",(f['parent'],))
    assert actor_claim(f)['outcome']=='claimed';assert catalog(f)['messages']==[]


def test_queued_and_running_actor_inputs_are_not_legacy_but_closed_native_results_are(source_facts):
    f=source_facts
    future=[add_image(f),add_image(f)]
    native=add_image(f,role='assistant')
    native_turn=str(uuid4())
    with psycopg.connect(f['dsn']) as db:
        for i,message in enumerate(future):
            turn=str(uuid4())
            db.execute('UPDATE messages SET turn_id=%s WHERE id=%s',(turn,message))
            db.execute("INSERT INTO tasks(id,user_id,conversation_id,type,status,turn_id,input_message_id,delivery_context,execution_mode) VALUES (%s,%s,%s,'chat',%s,%s,%s,'{\"actor\":true}','branch')",
                (str(uuid4()),f['user'],f['snapshot']['origin']['conversation_id'],'running' if i else 'pending',turn,message))
        db.execute('UPDATE messages SET turn_id=%s WHERE id=%s',(native_turn,native))
        db.execute("INSERT INTO tasks(id,user_id,conversation_id,type,status,turn_id,assistant_message_id) VALUES (%s,%s,%s,'image','completed',%s,%s)",
            (str(uuid4()),f['user'],f['snapshot']['origin']['conversation_id'],native_turn,native))
    assert actor_claim(f)['outcome']=='claimed'
    assert [row['id'] for row in catalog(f)['messages']]==[native]

@pytest.mark.asyncio
async def test_real_catalog_two_requests_and_worker_preserve_b_original_and_one_ledger_each(source_facts,lifecycle,monkeypatch):
    from types import SimpleNamespace
    from unittest.mock import AsyncMock,Mock
    from PIL import Image
    from services.file_executor import FileExecutor
    from services.handlers.chat_image_request import ChatImageInputResolver,freeze_image_request
    from services.handlers.chat_context.image_sources import legacy_catalog
    from services.adapters.base import ImageGenerateResult,TaskStatus
    from tests.test_chat_image_lifecycle_postgres import accept
    f=source_facts
    # Legacy image A was analysis; B is the only selected generation input.
    message=add_image(f,content=[{'type':'image','workspace_path':'A.png'},{'type':'image','workspace_path':'B.png'}])
    claimed=actor_claim(f);f['token']=claimed['execution_token']
    parent=lifecycle.db.table('tasks').select('*').eq('id',f['parent']).single().execute().data
    files=FileExecutor(lifecycle.settings.file_workspace_root,f['user'],None)
    for name,color in [('A.png','blue'),('B.png','red')]:Image.new('RGB',(4,4),color).save(files.resolve_safe_path(name))
    monkeypatch.setattr(FileExecutor,'get_cdn_url',lambda self,path:f'https://isolated.test/original/{path}')
    owner=SimpleNamespace(db=lifecycle.db,user_id=f['user'],workspace_user_id=f['user'],org_id=None,
        conversation_id=f['snapshot']['origin']['conversation_id'],context_scope='user',resource_manifest=None,execution_mode='interactive')
    refs=ChatImageInputResolver(owner,base_revision=0,input_message_id=parent['input_message_id'],files=files,
        legacy_sources=legacy_catalog(parent)).resolve([{'message_id':message,'content_index':1,'role':'product'}])
    task_ids=[]
    for n in range(2):
        frozen=freeze_image_request({'mode':'image_to_image','prompt':f'  精确原文{n}\n'},refs,
            origin={**f['snapshot']['origin'],'tool_call_id':f'ref-{n}'},max_requests=2,max_credits=24)
        task_ids.append(accept(f,frozen)['task_id'])
    adapter=Mock(generate=AsyncMock(side_effect=[ImageGenerateResult(task_id=f'offline-{n}',status=TaskStatus.PENDING) for n in range(2)]),close=AsyncMock())
    monkeypatch.setattr('services.adapters.factory.create_image_adapter',lambda *a,**kw:adapter)
    # Catalog/Worker restart and closed new-acceptance gate do not change input.
    add_image(f)
    for task_id in task_ids:
        await lifecycle.submit(await lifecycle.refresh({'id':task_id,'user_id':f['user'],'org_id':None}))
    assert adapter.generate.await_count==2
    for n,call in enumerate(adapter.generate.await_args_list):
        assert call.kwargs['prompt']==f'  精确原文{n}\n'
        assert call.kwargs['image_urls']==['https://isolated.test/original/B.png']
        assert call.kwargs['_chat_image_single_submit'] is True and call.kwargs['wait_for_result'] is False
    with psycopg.connect(f['dsn']) as db:
        assert db.execute('SELECT count(*) FROM credit_transactions WHERE task_id=ANY(%s::uuid[])',(task_ids,)).fetchone()[0]==2
        assert db.execute('SELECT credits_locked FROM tasks WHERE id=ANY(%s::uuid[])',(task_ids,)).fetchall()==[(6,),(6,)]
        assert db.execute('SELECT credits FROM users WHERE id=%s',(f['user'],)).fetchone()[0]==88


def test_rollback_preserves_owner_acl_and_catalog_data(source_facts):
    f=source_facts;add_image(f);actor_claim(f)
    frozen=catalog(f)
    db=psycopg.connect(f['dsn'])
    try:
        before=db.execute("SELECT pg_get_userbyid(proowner),prosecdef,proacl::text FROM pg_proc WHERE oid='claim_next_serial_generation_turn(uuid,integer,integer)'::regprocedure").fetchone()
        db.execute((ROOT/'migrations/rollback/277_chat_image_sources.sql').read_text())
        after=db.execute("SELECT pg_get_userbyid(proowner),prosecdef,proacl::text FROM pg_proc WHERE oid='claim_next_serial_generation_turn(uuid,integer,integer)'::regprocedure").fetchone()
        assert after==before
        assert db.execute("SELECT request_params->'_image_sources_v1' FROM tasks WHERE id=%s",(f['parent'],)).fetchone()[0]==frozen
        assert db.execute("SELECT to_regprocedure('freeze_chat_image_sources(tasks,conversations)')").fetchone()[0] is None
    finally:db.rollback();db.close()


@pytest.mark.asyncio
@pytest.mark.parametrize('mutation',['message_changed','original_deleted'])
async def test_selected_legacy_source_change_is_closed_without_provider_or_charge(source_facts,lifecycle,monkeypatch,mutation):
    from types import SimpleNamespace
    from unittest.mock import Mock
    from PIL import Image
    from services.file_executor import FileExecutor
    from services.handlers.chat_image_request import ChatImageInputResolver,freeze_image_request
    from services.handlers.chat_context.image_sources import legacy_catalog
    from tests.test_chat_image_lifecycle_postgres import accept
    f=source_facts
    message=add_image(f,content=[{'type':'image','workspace_path':'B.png'}])
    f['token']=actor_claim(f)['execution_token']
    parent=lifecycle.db.table('tasks').select('*').eq('id',f['parent']).single().execute().data
    files=FileExecutor(lifecycle.settings.file_workspace_root,f['user'],None)
    path=files.resolve_safe_path('B.png');Image.new('RGB',(4,4),'red').save(path)
    owner=SimpleNamespace(db=lifecycle.db,user_id=f['user'],workspace_user_id=f['user'],org_id=None,
        conversation_id=f['snapshot']['origin']['conversation_id'],context_scope='user',resource_manifest=None,execution_mode='interactive')
    refs=ChatImageInputResolver(owner,base_revision=0,input_message_id=parent['input_message_id'],files=files,
        legacy_sources=legacy_catalog(parent)).resolve([{'message_id':message,'content_index':0,'role':'product'}])
    task_id=accept(f,freeze_image_request({'mode':'image_to_image','prompt':'原文'},refs,
        origin={**f['snapshot']['origin'],'tool_call_id':'failure'},max_requests=2,max_credits=24))['task_id']
    if mutation=='message_changed':
        with psycopg.connect(f['dsn']) as db:db.execute("UPDATE messages SET content=%s WHERE id=%s",(json.dumps([{'type':'image','workspace_path':'A.png'}]),message))
    else:path.unlink()
    provider=Mock(side_effect=AssertionError('No paid IO'))
    monkeypatch.setattr('services.adapters.factory.create_image_adapter',provider)
    await lifecycle.submit(await lifecycle.refresh({'id':task_id,'user_id':f['user'],'org_id':None}))
    provider.assert_not_called()
    with psycopg.connect(f['dsn']) as db:
        assert db.execute("SELECT status,request_params->'_media_lifecycle_v1'->>'phase' FROM tasks WHERE id=%s",(task_id,)).fetchone()==('failed','published')
        assert db.execute('SELECT count(*) FROM credit_transactions WHERE task_id=%s',(task_id,)).fetchone()[0]==0
        assert db.execute('SELECT credits FROM users WHERE id=%s',(f['user'],)).fetchone()[0]==100


def test_catalog_scope_and_immutability_do_not_depend_on_legacy_table_rls(source_facts):
    """Production legacy tables use trusted services, not table-level RLS."""
    f=source_facts;good=add_image(f)
    add_image(f,org=str(uuid4()));add_image(f,conv=str(uuid4()))
    db=psycopg.connect(f['dsn'])
    try:
        for table in ('tasks','messages','conversations'):
            db.execute(f'ALTER TABLE {table} DISABLE ROW LEVEL SECURITY')
        db.execute('SET LOCAL ROLE everydayai')
        db.execute("SELECT set_config('app.actor_user_id',%s,true),set_config('app.org_id','',true),set_config('app.access_kind','runtime',true)",(f['user'],))
        claim=db.execute('SELECT claim_next_serial_generation_turn(%s)',(f['snapshot']['origin']['conversation_id'],)).fetchone()[0]
        assert claim['outcome']=='claimed'
        frozen=db.execute("SELECT request_params->'_image_sources_v1' FROM tasks WHERE id=%s",(f['parent'],)).fetchone()[0]
        assert [row['id'] for row in frozen['messages']]==[good]
        with pytest.raises(psycopg.Error,match='IMAGE_SOURCE_CATALOG_IMMUTABLE'):
            with db.transaction():
                db.execute("UPDATE tasks SET request_params=jsonb_set(request_params,'{_image_sources_v1}','{}') WHERE id=%s",(f['parent'],))
        with pytest.raises(psycopg.Error,match='IMAGE_SOURCE_CATALOG_SCOPE_DENIED'):
            with db.transaction():
                db.execute("SELECT freeze_chat_image_sources(jsonb_populate_record(t,jsonb_build_object('user_id',%s::uuid)),c) FROM tasks t JOIN conversations c ON c.id=t.conversation_id WHERE t.id=%s",(str(uuid4()),f['parent']))
        for spoof in ('actor','org','token'):
            with pytest.raises(psycopg.Error,match='CHAT_IMAGE_(SCOPE_DENIED|PARENT_DENIED|FENCING_LOST)'):
                with db.transaction():
                    if spoof in ('actor','org'):
                        setting='app.actor_user_id' if spoof=='actor' else 'app.org_id'
                        db.execute('SELECT set_config(%s,%s,true)',(setting,str(uuid4())))
                    token=str(uuid4()) if spoof=='token' else claim['execution_token']
                    db.execute('SELECT accept_chat_image_request(%s,%s,%s,NULL)',(f['parent'],token,Jsonb(f['snapshot'])))
        assert db.execute("SELECT count(*) FROM tasks WHERE type='image' AND conversation_id=%s",(f['snapshot']['origin']['conversation_id'],)).fetchone()[0]==0
        assert db.execute('SELECT count(*) FROM credit_transactions WHERE user_id=%s',(f['user'],)).fetchone()[0]==0
        assert db.execute('SELECT credits FROM users WHERE id=%s',(f['user'],)).fetchone()[0]==100
    finally:
        # Test-only RLS toggles/claim are rolled back; no shared schema change.
        db.rollback();db.close()
