/**
 * 聊天模型配置
 *
 * 包含所有聊天类型模型的定义（KIE、Google、国内、OpenRouter）
 */

import { SMART_MODEL } from './smartModel';
import { type UnifiedModel } from './modelTypes';

export const CHAT_MODELS: UnifiedModel[] = [
  // 智能模型（配置见 smartModel.ts）
  SMART_MODEL,

  // KIE 聊天模型
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    type: 'chat',
    description: '快速响应 | 多模态理解',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: true,
      audioInput: true,
      pdfInput: true,
      functionCalling: true,
      structuredOutput: true,
      thinkingEffort: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxAudioSize: 25,
      maxVideoSize: 100,
      maxPDFSize: 50,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    type: 'chat',
    description: '高级推理 | Pro 级多模态',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: true,
      audioInput: true,
      pdfInput: true,
      functionCalling: true,
      structuredOutput: true,
      thinkingEffort: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxAudioSize: 25,
      maxVideoSize: 100,
      maxPDFSize: 50,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },

  // Google 官方模型（免费层）
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash ⚡️',
    type: 'chat',
    description: 'Google 官方 | 免费 | 快速响应',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: true,
      audioInput: true,
      pdfInput: true,
      functionCalling: true,
      structuredOutput: true,
      thinkingEffort: false,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxAudioSize: 25,
      maxVideoSize: 100,
      maxPDFSize: 50,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro 🚀',
    type: 'chat',
    description: 'Google 官方 | 免费 | 高级推理',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: true,
      audioInput: true,
      pdfInput: true,
      functionCalling: true,
      structuredOutput: true,
      thinkingEffort: false,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxAudioSize: 25,
      maxVideoSize: 100,
      maxPDFSize: 50,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },

  // 国内模型（DashScope 百炼）
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    type: 'chat',
    description: 'Agent 极强 | 百万上下文 | 开源最强',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: false,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    type: 'chat',
    description: '高性价比 | 百万上下文 | 速度快',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: false,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
  {
    id: 'deepseek-v3.2',
    name: 'DeepSeek V3.2',
    type: 'chat',
    description: '代码/数学极强 | 速度快费用低',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: false,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 131072,
    },
    credits: 0,
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    type: 'chat',
    description: '深度推理 | 数学/逻辑极强',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: false,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 131072,
    },
    credits: 0,
  },
  {
    id: 'qwen3.5-plus',
    name: 'Qwen 3.5 Plus',
    type: 'chat',
    description: '百万上下文 | 性价比之王',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    type: 'chat',
    description: '全能模型 | 图片理解 | 26万上下文',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 262144,
    },
    credits: 0,
  },
  {
    id: 'glm-5',
    name: 'GLM 5',
    type: 'chat',
    description: '中文能力强 | 20万上下文',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: false,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 202752,
    },
    credits: 0,
  },

  // OpenRouter 海外模型
  {
    id: 'openai/gpt-4.1',
    name: 'GPT-4.1',
    type: 'chat',
    description: 'OpenAI 旗舰 | 百万上下文 | 代码推理',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 1047576,
    },
    credits: 0,
  },
  {
    id: 'openai/gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    type: 'chat',
    description: 'OpenAI 轻量 | 百万上下文 | 费用低',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 1047576,
    },
    credits: 0,
  },
  {
    id: 'openai/o4-mini',
    name: 'o4-mini',
    type: 'chat',
    description: 'OpenAI 推理 | 深度思考 | 数学逻辑',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 200000,
    },
    credits: 0,
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4',
    type: 'chat',
    description: 'Anthropic | 代码分析创作 | 安全可靠',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 200000,
    },
    credits: 0,
  },
  {
    id: 'x-ai/grok-4.1-fast',
    name: 'Grok 4.1 Fast',
    type: 'chat',
    description: 'xAI | 200万上下文 | 极便宜',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: false,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxContextTokens: 2000000,
    },
    credits: 0,
  },
  {
    id: 'openai/gpt-5.4',
    name: 'GPT-5.4',
    type: 'chat',
    description: 'OpenAI 最新旗舰 | 百万上下文 | 全能',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 1050000,
    },
    credits: 0,
  },
  {
    id: 'openai/gpt-5.4-pro',
    name: 'GPT-5.4 Pro',
    type: 'chat',
    description: 'OpenAI 最强推理 | 极致性能 | 费用高',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 1050000,
    },
    credits: 0,
  },
  {
    id: 'openai/gpt-5.3-codex',
    name: 'GPT-5.3 Codex',
    type: 'chat',
    description: 'OpenAI 最强代码 | 编程第一 | 40万上下文',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 400000,
    },
    credits: 0,
  },
  {
    id: 'google/gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro',
    type: 'chat',
    description: 'Google 最新旗舰 | 全模态 | 百万上下文',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: true,
      audioInput: true,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxAudioSize: 25,
      maxVideoSize: 100,
      maxContextTokens: 1048576,
    },
    credits: 0,
  },
  {
    id: 'anthropic/claude-sonnet-4.6',
    name: 'Claude Sonnet 4.6',
    type: 'chat',
    description: 'Anthropic 最新 | 百万上下文 | Agent 极强',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
  {
    id: 'anthropic/claude-opus-4.6',
    name: 'Claude Opus 4.6',
    type: 'chat',
    description: 'Anthropic 最强 | 深度推理 | 复杂任务',
    capabilities: {
      textToImage: false,
      imageEditing: false,
      imageToVideo: false,
      textToVideo: false,
      vqa: true,
      videoQA: false,
      functionCalling: true,
      streamingResponse: true,
      maxImages: 10,
      maxFileSize: 20,
      maxContextTokens: 1000000,
    },
    credits: 0,
  },
];
