"""
售后 API注册表

包含：售后工单、退货入仓、补款、维修单、售后日志 相关API
"""

from services.kuaimai.registry.base import ApiEntry

AFTERSALES_REGISTRY = {
    # ── 查询 ──────────────────────────────────────────
    "aftersale_list": ApiEntry(
        method="erp.aftersale.list.query",
        description="售后工单查询",
        param_map={
            "order_id": "tid",
            "work_order_id": "id",
            "work_order_ids": "ids",
            "order_ids": "tids",
            "type": "afterSaleType",
            "as_version": "asVersion",
            "shop_ids": "userIds",
            "warehouse_ids": "warehouseIds",
            "start_date": "startModified",
            "end_date": "endModified",
            "start_apply": "startApplyTime",
            "end_apply": "endApplyTime",
            "start_finished": "startFinished",
            "end_finished": "endFinished",
            "platform_id": "platformId",
            "express_ids": "expressIds",
            "reissue_sid": "reissueSid",
            "suite_single": "suiteSingle",
        },
        defaults={"asVersion": 2},
        formatter="format_aftersale_list",
    ),
    "refund_warehouse": ApiEntry(
        method="erp.aftersale.refund.warehouse.query",
        description="销退入库单查询",
        param_map={
            "work_order_ids": "workOrderIds",
            "ids": "ids",
            "shop_ids": "userIds",
            "warehouse_ids": "warehouseIds",
            "status": "status",
            "time_type": "timeType",
            "start_date": "startTime",
            "end_date": "endTime",
            "buyer_name": "buyerName",
            "wangwang": "wangwangNum",
        },
        formatter="format_refund_warehouse",
    ),
    "replenish_list": ApiEntry(
        method="erp.aftersale.replenish.list.query",
        description="登记补款查询",
        param_map={
            "order_id": "tid",
            "work_order_id": "id",
            "shop_ids": "userIds",
            "status": "status",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        formatter="format_replenish_list",
    ),
    "repair_list": ApiEntry(
        method="erp.aftersale.repair.list.query",
        description="维修单列表查询",
        param_map={
            "status": "repairStatus",
            "time_type": "timeType",
            "start_date": "timeStart",
            "end_date": "timeEnd",
            "query_type": "queryType",
            "query_text": "queryText",
        },
        formatter="format_repair_list",
    ),
    "repair_detail": ApiEntry(
        method="erp.aftersale.repair.detail.query",
        description="维修单详情查询",
        param_map={
            "repair_no": "repairOrderNum",
        },
        required_params=["repair_no"],
        formatter="format_repair_detail",
        response_key=None,
    ),
    "aftersale_log": ApiEntry(
        method="erp.aftersale.operate.log.query",
        description="售后日志查询",
        param_map={
            "work_order_id": "workOrderId",
        },
        required_params=["work_order_id"],
        formatter="format_aftersale_log",
    ),
    # ── 写入操作 ──────────────────────────────────────
    "workorder_create": ApiEntry(
        method="erp.aftersale.workorder.create",
        description="创建售后工单",
        param_map={
            "order_id": "tid",
            "system_id": "sid",
            "shop_id": "userId",
            "warehouse_id": "refundWarehouseId",
            "reason": "reason",
            "after_sale_type": "afterSaleType",
            "reissue_list": "reissueOrRefundList",
            "has_owner": "hasOwner",
            "remark": "remark",
            "platform_id": "platformId",
            "buyer_name": "buyerName",
            "buyer_phone": "buyerPhone",
            "explains": "explains",
            "force": "force",
        },
        required_params=["warehouse_id", "reason", "after_sale_type", "reissue_list"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认创建售后工单？",
    ),
    "workorder_cancel": ApiEntry(
        method="erp.aftersale.workorder.cancel",
        description="作废售后工单",
        param_map={
            "work_order_ids": "workOrderIds",
        },
        required_params=["work_order_ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废售后工单？此操作不可逆！",
    ),
    "workorder_resolve": ApiEntry(
        method="erp.aftersale.workorder.resolve",
        description="解决售后工单",
        param_map={
            "work_order_ids": "workOrderIds",
        },
        required_params=["work_order_ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_goods_received": ApiEntry(
        method="erp.aftersale.workorder.goods.received",
        description="售后工单退货入仓",
        param_map={
            "warehouse_id": "warehouseId",
            "external_warehouse_code": "externalWarehouseCode",
            "received_orders": "receivedAsOrders",
        },
        required_params=["received_orders"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_tag_update": ApiEntry(
        method="erp.aftersale.workorder.tag.update",
        description="更新售后工单标记",
        param_map={
            "type": "type",
            "work_order_id": "workOrderId",
            "tag_names": "tagNames",
            "tag_ids": "tagIds",
        },
        required_params=["type", "work_order_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_explains_update": ApiEntry(
        method="erp.aftersale.workorder.explains.update",
        description="更新售后单售后说明",
        param_map={
            "work_order_id": "workOrderId",
            "explains": "explains",
            "is_append": "isAppend",
        },
        required_params=["work_order_id", "explains"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_batch_change_type": ApiEntry(
        method="erp.aftersale.workorder.batchChangeType",
        description="批量修改售后类型",
        param_map={
            "work_order_ids": "workOrderIds",
            "change_type": "changeType",
        },
        required_params=["work_order_ids", "change_type"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "repair_process": ApiEntry(
        method="erp.aftersale.repair.order.process",
        description="维修单处理",
        param_map={
            "repair_no": "repairOrderNum",
            "has_fee": "hasFee",
            "failure_cause": "failureCause",
            "repair_remark": "repairRemark",
            "accessory_url": "accessoryUrl",
        },
        required_params=["repair_no"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "repair_edit_money": ApiEntry(
        method="erp.aftersale.repair.order.edit.repairMoney",
        description="维修单修改费用",
        param_map={
            "repair_no": "repairOrderNum",
            "repair_money": "repairMoney",
        },
        required_params=["repair_no", "repair_money"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "repair_pay": ApiEntry(
        method="erp.aftersale.repair.order.pay",
        description="维修单付款",
        param_map={
            "repair_no": "repairOrderNum",
            "received_time": "receivedTime",
            "received_way": "receivedWay",
            "current_price": "currentPrice",
            "trade_number": "tradeNumber",
            "operator_name": "operatorName",
            "operator_time": "operatorTime",
        },
        required_params=["repair_no"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_remark_update": ApiEntry(
        method="erp.aftersale.workorder.remark.update",
        description="修改售后工单备注",
        param_map={
            "work_order_id": "workOrderId",
            "remark": "remark",
        },
        required_params=["work_order_id", "remark"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "update_platform_refund_money": ApiEntry(
        method="erp.aftersale.update.platformRefundMoney",
        description="更新工单平台实退金额",
        param_map={
            "work_order_id": "id",
            "platform_refund_money": "platformRefundMoney",
            "item_snapshot": "itemSnapshot",
        },
        required_params=["work_order_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "update_express": ApiEntry(
        method="erp.aftersale.update.express",
        description="更新工单退货快递信息",
        param_map={
            "work_order_id": "id",
            "platform_id": "platformId",
            "express_name": "expressName",
            "express_id": "expressId",
        },
        required_params=["work_order_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
}
