"""
售后 API注册表

包含：售后工单、退货入仓、补款、维修单、售后日志 相关API
"""

from services.kuaimai.registry.base import ApiEntry

AFTERSALES_REGISTRY = {
    # ── 查询 ──────────────────────────────────────────
    "aftersale_list": ApiEntry(
        method="erp.aftersale.list.query",
        description="售后工单查询",
        param_map={
            "order_id": "tid",
            "work_order_id": "id",
            "work_order_ids": "ids",
            "order_ids": "tids",
            "type": "afterSaleType",
            "as_version": "asVersion",
            "shop_ids": "userIds",
            "warehouse_ids": "warehouseIds",
            "start_date": "startModified",
            "end_date": "endModified",
            "start_apply": "startApplyTime",
            "end_apply": "endApplyTime",
            "start_finished": "startFinished",
            "end_finished": "endFinished",
            "platform_id": "platformId",
            "express_ids": "expressIds",
            "reissue_sid": "reissueSid",
            "suite_single": "suiteSingle",
        },
        param_docs={
            "order_id": "平台订单号。示例: 126036803257340376",
            "work_order_id": "售后工单ID（单个）。示例: 50001",
            "work_order_ids": "售后工单ID（多个逗号隔开）。示例: 50001,50002",
            "order_ids": "平台订单号（多个逗号隔开）。示例: 126036803257340376,126036803257340377",
            "type": "售后类型。可选值: 0=其他, 1=已发货仅退款, 2=退货, 3=补发, 4=换货, 5=未发货仅退款, 7=拒收退货, 8=档口退货, 9=维修。示例: 2",
            "as_version": "售后版本。默认2。可选值: 1(旧版), 2(新版)。示例: 2",
            "shop_ids": "店铺ID（多个逗号隔开，通过shop_list获取）。示例: 12345,67890",
            "warehouse_ids": "仓库ID（多个逗号隔开，通过warehouse_list获取）。示例: 1001,1002",
            "start_date": "起始修改日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束修改日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "start_apply": "起始申请日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_apply": "结束申请日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "start_finished": "起始完结日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_finished": "结束完结日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "platform_id": "平台退款单号。示例: RF20260301001",
            "express_ids": "快递单号（多个逗号隔开）。示例: SF1234567890",
            "reissue_sid": "补发系统单号。示例: 5759422420146938",
            "suite_single": "是否套装拆单。可选值: 0(否), 1(是)。示例: 0",
        },
        defaults={"asVersion": 2},
        formatter="format_aftersale_list",
    ),
    "refund_warehouse": ApiEntry(
        method="erp.aftersale.refund.warehouse.query",
        description="销退入库单查询",
        param_map={
            "work_order_ids": "workOrderIds",
            "ids": "ids",
            "shop_ids": "userIds",
            "warehouse_ids": "warehouseIds",
            "status": "status",
            "time_type": "timeType",
            "start_date": "startTime",
            "end_date": "endTime",
            "buyer_name": "buyerName",
            "wangwang": "wangwangNum",
        },
        param_docs={
            "work_order_ids": "售后工单ID（多个逗号隔开）。示例: 50001,50002",
            "ids": "销退入库单ID（多个逗号隔开）。示例: 60001,60002",
            "shop_ids": "店铺ID（多个逗号隔开，通过shop_list获取）。示例: 12345,67890",
            "warehouse_ids": "仓库ID（多个逗号隔开，通过warehouse_list获取）。示例: 1001,1002",
            "status": "入库状态。可选值: 1=等待收货, 2=上架完成, 3=等待上架, 4=已作废, 5=部分上架。示例: 1",
            "time_type": "时间类型（必填）。可选值: createTime(创建时间), modifyTime(修改时间), endTime(完结时间), receiveGoodsTime(收货时间), disposeSuc(处理成功时间)。示例: createTime",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "buyer_name": "买家姓名。示例: 张三",
            "wangwang": "买家旺旺号。示例: tb_buyer123",
        },
        required_params=["time_type"],
        formatter="format_refund_warehouse",
    ),
    "replenish_list": ApiEntry(
        method="erp.aftersale.replenish.list.query",
        description="登记补款查询",
        param_map={
            "order_id": "tid",
            "work_order_id": "id",
            "shop_ids": "userIds",
            "status": "status",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "order_id": "平台订单号。示例: 126036803257340376",
            "work_order_id": "售后工单ID。示例: 50001",
            "shop_ids": "店铺ID（多个逗号隔开，通过shop_list获取）。示例: 12345,67890",
            "status": "补款状态。可选值: 0(待补款), 1(已补款), 2(已作废)。示例: 0",
            "start_date": "起始修改日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束修改日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_replenish_list",
    ),
    "repair_list": ApiEntry(
        method="erp.aftersale.repair.list.query",
        description="维修单列表查询",
        param_map={
            "status": "repairStatus",
            "time_type": "timeType",
            "start_date": "timeStart",
            "end_date": "timeEnd",
            "query_type": "queryType",
            "query_text": "queryText",
        },
        param_docs={
            "status": "维修状态。可选值: 0=待审核, 1=待收货, 2=待维修, 3=待寄出, 4=已完成, -1=已作废。示例: 0",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间), returnTime(退货时间)。示例: create",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "query_type": "查询类型。可选值: 1(维修单号), 2(订单号), 3(买家昵称)。示例: 1",
            "query_text": "查询关键字。配合query_type使用。示例: RX20260301001",
        },
        formatter="format_repair_list",
    ),
    "repair_detail": ApiEntry(
        method="erp.aftersale.repair.detail.query",
        description="维修单详情查询",
        param_map={
            "repair_no": "repairOrderNum",
        },
        param_docs={
            "repair_no": "维修单号（必填）。示例: RX20260301001",
        },
        required_params=["repair_no"],
        formatter="format_repair_detail",
        response_key=None,
    ),
    "aftersale_log": ApiEntry(
        method="erp.aftersale.operate.log.query",
        description="售后日志查询",
        param_map={
            "work_order_id": "workOrderId",
        },
        param_docs={
            "work_order_id": "售后工单ID（必填）。示例: 50001",
        },
        required_params=["work_order_id"],
        formatter="format_aftersale_log",
    ),
    # ── 写入操作 ──────────────────────────────────────
    "workorder_create": ApiEntry(
        method="erp.aftersale.workorder.create",
        description="创建售后工单",
        param_map={
            "order_id": "tid",
            "system_id": "sid",
            "shop_id": "userId",
            "warehouse_id": "refundWarehouseId",
            "reason": "reason",
            "after_sale_type": "afterSaleType",
            "reissue_list": "reissueOrRefundList",
            "has_owner": "hasOwner",
            "remark": "remark",
            "platform_id": "platformId",
            "buyer_name": "buyerName",
            "buyer_phone": "buyerPhone",
            "explains": "explains",
            "force": "force",
        },
        required_params=["warehouse_id", "reason", "after_sale_type", "reissue_list"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认创建售后工单？",
    ),
    "workorder_cancel": ApiEntry(
        method="erp.aftersale.workorder.cancel",
        description="作废售后工单",
        param_map={
            "work_order_ids": "workOrderIds",
        },
        required_params=["work_order_ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废售后工单？此操作不可逆！",
    ),
    "workorder_resolve": ApiEntry(
        method="erp.aftersale.workorder.resolve",
        description="解决售后工单",
        param_map={
            "work_order_ids": "workOrderIds",
        },
        required_params=["work_order_ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_goods_received": ApiEntry(
        method="erp.aftersale.workorder.goods.received",
        description="售后工单退货入仓",
        param_map={
            "warehouse_id": "warehouseId",
            "external_warehouse_code": "externalWarehouseCode",
            "received_orders": "receivedAsOrders",
        },
        required_params=["received_orders"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_tag_update": ApiEntry(
        method="erp.aftersale.workorder.tag.update",
        description="更新售后工单标记",
        param_map={
            "type": "type",
            "work_order_id": "workOrderId",
            "tag_names": "tagNames",
            "tag_ids": "tagIds",
        },
        required_params=["type", "work_order_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_explains_update": ApiEntry(
        method="erp.aftersale.workorder.explains.update",
        description="更新售后单售后说明",
        param_map={
            "work_order_id": "workOrderId",
            "explains": "explains",
            "is_append": "isAppend",
        },
        required_params=["work_order_id", "explains", "is_append"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_batch_change_type": ApiEntry(
        method="erp.aftersale.workorder.batchChangeType",
        description="批量修改售后类型",
        param_map={
            "work_order_ids": "workOrderIds",
            "change_type": "changeType",
        },
        required_params=["work_order_ids", "change_type"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "repair_process": ApiEntry(
        method="erp.aftersale.repair.order.process",
        description="维修单处理",
        param_map={
            "repair_no": "repairOrderNum",
            "has_fee": "hasFee",
            "failure_cause": "failureCause",
            "repair_remark": "repairRemark",
            "accessory_url": "accessoryUrl",
        },
        required_params=["repair_no", "has_fee", "failure_cause"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "repair_edit_money": ApiEntry(
        method="erp.aftersale.repair.order.edit.repairMoney",
        description="维修单修改费用",
        param_map={
            "repair_no": "repairOrderNum",
            "repair_money": "repairMoney",
        },
        required_params=["repair_no", "repair_money"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "repair_pay": ApiEntry(
        method="erp.aftersale.repair.order.pay",
        description="维修单付款",
        param_map={
            "repair_no": "repairOrderNum",
            "received_time": "receivedTime",
            "received_way": "receivedWay",
            "current_price": "currentPrice",
            "trade_number": "tradeNumber",
            "operator_name": "operatorName",
            "operator_time": "operatorTime",
        },
        required_params=["repair_no", "received_time", "current_price"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "workorder_remark_update": ApiEntry(
        method="erp.aftersale.workorder.remark.update",
        description="修改售后工单备注",
        param_map={
            "work_order_id": "workOrderId",
            "remark": "remark",
        },
        required_params=["work_order_id", "remark"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "update_platform_refund_money": ApiEntry(
        method="erp.aftersale.update.platformRefundMoney",
        description="更新工单平台实退金额",
        param_map={
            "work_order_id": "id",
            "platform_refund_money": "platformRefundMoney",
            "item_snapshot": "itemSnapshot",
        },
        required_params=["work_order_id", "platform_refund_money"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "update_express": ApiEntry(
        method="erp.aftersale.update.express",
        description="更新工单退货快递信息",
        param_map={
            "work_order_id": "id",
            "platform_id": "platformId",
            "express_name": "expressName",
            "express_id": "expressId",
        },
        required_params=["work_order_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
}
