"""
商品 API注册表

包含：商品查询/管理、SKU、标签、分类、品牌、供应商关系、库存 相关API
"""

from services.kuaimai.registry.base import ApiEntry

PRODUCT_REGISTRY = {
    # ── 商品查询 ──────────────────────────────────────
    "product_list": ApiEntry(
        method="item.list.query",
        description="查询商品列表",
        param_map={
            "keyword": "keyword",
            "status": "activeStatus",
            "start_date": "startModified",
            "end_date": "endModified",
            "item_type": "type",
            "order_by": "orderBy",
            "return_purchase": "whetherReturnPurchase",
        },
        param_docs={
            "keyword": "按商品名称模糊搜索。有编码时用outer_id更精准。示例: 手机壳",
            "status": "商品状态。可选值: 0=停用, 1=启用",
            "start_date": "起始修改日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束修改日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "item_type": "商品类型。可选值: 0=单品, 1=套件, 3=组合装, 6=虚拟商品, 7=服务商品, 8=加工商品, 9=包材, 10=赠品",
            "order_by": "排序方式。格式: 字段:方向。示例: created:desc, modified:asc",
            "return_purchase": "是否返回采购信息。可选值: 0=不返回, 1=返回",
        },
        error_codes={
            "50": "商品类型数值不合法（只能选0/1/3/6/7/8/9/10）",
            "20001": "页码为空或不符合规定",
            "20002": "页数为空或不符合规定",
            "20004": "排序方式不正确",
            "20103": "查询商品列表有误",
            "20109": "系统商品状态不正确",
        },
        formatter="format_product_list",
        response_key="items",
    ),
    "product_detail": ApiEntry(
        method="item.single.get",
        description="查询单个商品明细",
        param_map={
            "item_id": "sysItemId",
            "outer_id": "outerId",
            "return_purchase": "whetherReturnPurchase",
        },
        param_docs={
            "item_id": "快麦系统商品ID（数字ID）。仅在从其他查询结果获取到时使用",
            "outer_id": "商家编码（最常用的商品识别方式）。示例: ABC123",
            "return_purchase": "是否返回采购信息。可选值: 0=不返回, 1=返回",
        },
        error_codes={
            "20105": "系统主商品ID与平台商家编码必须二选一",
            "20110": "查询商品信息有误",
        },
        formatter="format_product_detail",
        response_key=None,
    ),
    "sku_info": ApiEntry(
        method="erp.item.single.sku.get",
        description="查询商品SKU信息",
        param_map={
            "sku_id": "sysSkuId",
            "sku_outer_id": "skuOuterId",
            "return_purchase": "whetherReturnPurchase",
        },
        param_docs={
            "sku_id": "SKU系统ID。仅在从其他查询结果获取到时使用",
            "sku_outer_id": "SKU商家编码（多个逗号隔开）。示例: SKU001,SKU002",
            "return_purchase": "是否返回采购信息。可选值: 0=不返回, 1=返回",
        },
        error_codes={
            "20106": "系统商品skuID与平台规格商家编码必须二选一",
            "20107": "查询商品SKU信息有误",
        },
        formatter="format_sku_info",
        response_key=None,
    ),
    "sku_list": ApiEntry(
        method="erp.item.sku.list.get",
        description="查询商品SKU列表V2",
        param_map={
            "outer_id": "outerId",
            "item_id": "sysItemId",
            "return_purchase": "whetherReturnPurchase",
        },
        param_docs={
            "outer_id": "商家编码（最常用的商品识别方式）。示例: ABC123",
            "item_id": "快麦系统商品ID（数字ID）。仅在从其他查询结果获取到时使用",
            "return_purchase": "是否返回采购信息。可选值: 0=不返回, 1=返回",
        },
        error_codes={
            "20104": "查询商品SKU列表有误",
            "20105": "系统主商品ID与平台商家编码必须二选一",
        },
        formatter="format_sku_info",
        response_key="itemSkus",
    ),
    "multi_product": ApiEntry(
        method="erp.item.list.get",
        description="查询多个商品信息V2",
        param_map={
            "outer_ids": "outerIds",
            "item_ids": "sysItemIds",
            "return_skus": "returnSkus",
        },
        param_docs={
            "outer_ids": "多个商家编码（逗号隔开）。示例: ABC123,DEF456",
            "item_ids": "多个系统商品ID（逗号隔开）。示例: 10001,10002",
            "return_skus": "是否返回SKU信息。可选值: 0=不返回, 1=返回。默认返回",
        },
        defaults={"returnSkus": 1},
        error_codes={
            "20103": "查询商品列表有误",
            "20105": "系统主商品ID与平台商家编码必须二选一",
            "20111": "系统主商品ID最多支持20组",
            "20112": "平台商家编码最多支持20组",
            "20113": "系统主商品ID信息不正确",
        },
        formatter="format_product_list",
        response_key="items",
    ),
    "multicode_query": ApiEntry(
        method="erp.item.multicode.query",
        description="商品多码查询",
        param_map={
            "code": "code",
            "barcode": "code",
        },
        param_docs={
            "code": "商品条码。示例: 6901234567890",
            "barcode": "商品条码（code的别名）。示例: 6901234567890",
        },
        required_params=["code"],
        formatter="format_product_list",
        response_key="list",
    ),
    # ── 库存查询 ──────────────────────────────────────
    "stock_status": ApiEntry(
        method="stock.api.status.query",
        description="查询库存状态",
        param_map={
            "outer_id": "mainOuterId",
            "sku_outer_id": "skuOuterId",
            "warehouse_id": "warehouseId",
            "stock_statuses": "stockStatuses",
            "item_type": "itemType",
            "brand": "brands",
            "created": "created",
            "modified": "modified",
            "stock_start": "startStockModified",
            "stock_end": "endStockModified",
            "relation_fields": "relationInfoFields",
        },
        param_docs={
            "outer_id": "商家编码（最常用的商品识别方式）。示例: ABC123",
            "sku_outer_id": "SKU商家编码（多个逗号隔开）。示例: SKU001,SKU002",
            "warehouse_id": "仓库ID（通过warehouse_list获取）",
            "stock_statuses": "库存状态筛选（多个逗号隔开）。可选值: 1=正常, 2=警戒, 3=无货, 4=超卖, 6=有货。示例: 1,2",
            "item_type": "商品类型。可选值: 0=单品, 1=套件, 2=组合装, 3=加工",
            "brand": "品牌名称（多个逗号隔开）。示例: 品牌A,品牌B",
            "created": "创建日期。格式: YYYY-MM-DD",
            "modified": "修改日期。格式: YYYY-MM-DD",
            "stock_start": "库存变动起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "stock_end": "库存变动结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "relation_fields": "关联信息字段。指定需要额外返回的关联信息",
        },
        error_codes={
            "50": "库存状态不合法",
            "20001": "页码为空或不符合规定",
            "20002": "页数为空或不符合规定",
            "20019": "页数不能超过100",
            "20305": "仓库ID不能为空或小于0",
            "20307": "商品类型不合法",
        },
        formatter="format_inventory_list",
        response_key="stockStatusVoList",
        page_size=50,
    ),
    "warehouse_stock": ApiEntry(
        method="erp.item.warehouse.list.get",
        description="查询仓库及商品库存信息",
        param_map={
            "outer_id": "outerId",
            "sku_outer_id": "skuOuterId",
        },
        param_docs={
            "outer_id": "商家编码（最常用的商品识别方式）。示例: ABC123",
            "sku_outer_id": "SKU商家编码（多个逗号隔开）。示例: SKU001,SKU002",
        },
        error_codes={
            "20301": "主商家编码与SKU商家编码必须二选一",
            "20302": "平台商家编码不支持多个查询",
            "20303": "平台规格商家编码不支持多个查询",
            "20304": "查询仓库及商品库存信息有误",
        },
        formatter="format_warehouse_stock",
    ),
    "stock_in_out": ApiEntry(
        method="erp.item.stock.in.out.list",
        description="查询商品出入库记录",
        param_map={
            "outer_id": "outerId",
            "warehouse_id": "warehouseId",
            "start_date": "operateTimeBegin",
            "end_date": "operateTimeEnd",
            "order_type": "orderType",
            "order_number": "orderNumber",
        },
        param_docs={
            "outer_id": "商家编码（最常用的商品识别方式）。示例: ABC123",
            "warehouse_id": "仓库ID（通过warehouse_list获取）",
            "start_date": "起始操作日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束操作日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "order_type": "单据类型。可选值: 1=采购入库, 2=销售出库, 3=盘盈入库, 4=盘亏出库, 5=调拨入库, 6=调拨出库",
            "order_number": "单据编号。精确匹配",
        },
        formatter="format_stock_in_out",
    ),
    "virtual_warehouse": ApiEntry(
        method="erp.virtual.warehouse.query",
        description="查询虚拟仓",
        param_map={
            "name": "name",
        },
        param_docs={
            "name": "虚拟仓名称（模糊搜索）。示例: 预售仓",
        },
        formatter="format_generic_list",
        response_key="list",
    ),
    "history_cost_price": ApiEntry(
        method="erp.item.history.cost.price.query",
        description="商品历史成本价查询",
        param_map={
            "item_id": "sysItemId",
            "sku_id": "sysSkuId",
            "start_date": "startTime",
            "end_date": "endTime",
            "warehouse_ids": "warehouseIdList",
        },
        param_docs={
            "item_id": "快麦系统商品ID（数字ID）。必填。仅在从其他查询结果获取到时使用",
            "sku_id": "SKU系统ID。必填。仅在从其他查询结果获取到时使用",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "warehouse_ids": "仓库ID列表（通过warehouse_list获取）。多个逗号隔开",
        },
        required_params=["item_id", "sku_id"],
        formatter="format_generic_list",
    ),
    # ── 标签/分类/品牌 查询 ────────────────────────────
    "tag_list": ApiEntry(
        method="erp.item.tag.list",
        description="查询商品标签",
        param_map={"name": "name"},
        param_docs={
            "name": "标签名称（模糊搜索）。不传则返回所有标签。示例: 爆款",
        },
        fetch_all=True,
        page_size=500,
        formatter="format_tag_list",
    ),
    "cat_list": ApiEntry(
        method="erp.item.seller.cat.list.get",
        description="查询商品分类信息",
        fetch_all=True,
        page_size=500,
        formatter="format_generic_list",
        response_key="sellerCats",
    ),
    "classify_list": ApiEntry(
        method="item.classify.list.get",
        description="查询商品类目信息",
        error_codes={
            "20101": "查询类目列表有误",
        },
        fetch_all=True,
        page_size=500,
        formatter="format_generic_list",
        response_key="classifies",
    ),
    "brand_list": ApiEntry(
        method="brand.list.get",
        description="查询商品品牌信息",
        error_codes={
            "20001": "页码为空或不符合规定",
            "20002": "页数为空或不符合规定",
            "20102": "查询品牌列表有误",
        },
        fetch_all=True,
        page_size=500,
        formatter="format_generic_list",
        response_key="items",
    ),
    # ── 对应关系/供应商 查询 ────────────────────────────
    "outer_id_list": ApiEntry(
        method="erp.item.outerid.list.get",
        description="商品对应关系查询",
        param_map={
            "outer_ids": "outerIds",
            "platform_ids": "numIidList",
            "shop_id": "userId",
            "taobao_id": "taobaoId",
        },
        param_docs={
            "outer_ids": "多个商家编码（逗号隔开）。示例: ABC123,DEF456",
            "platform_ids": "平台商品ID。多个逗号隔开",
            "shop_id": "店铺ID（通过shop_list获取）",
            "taobao_id": "淘宝商品ID",
        },
        formatter="format_generic_list",
        response_key="itemOuterIdInfos",
    ),
    "outer_id_by_item": ApiEntry(
        method="erp.item.outerid.list.byitem.get",
        description="商品对应关系查询(按商品ID)",
        param_map={
            "platform_ids": "numIidList",
            "shop_id": "userId",
            "taobao_id": "taobaoId",
        },
        param_docs={
            "platform_ids": "平台商品ID。必填。多个逗号隔开",
            "shop_id": "店铺ID（通过shop_list获取）",
            "taobao_id": "淘宝商品ID",
        },
        required_params=["platform_ids"],
        formatter="format_generic_list",
        response_key="itemOuterIdInfos",
    ),
    "item_supplier_list": ApiEntry(
        method="erp.item.supplier.list.get",
        description="查询商品关联供应商信息",
        param_map={
            "item_ids": "sysItemIds",
            "sku_ids": "sysSkuIds",
            "outer_ids": "outerIds",
            "sku_outer_ids": "skuOuterIds",
        },
        param_docs={
            "item_ids": "多个系统商品ID（逗号隔开）。示例: 10001,10002",
            "sku_ids": "多个SKU系统ID（逗号隔开）",
            "outer_ids": "多个商家编码（逗号隔开）。示例: ABC123,DEF456",
            "sku_outer_ids": "多个SKU商家编码（逗号隔开）。示例: SKU001,SKU002",
        },
        error_codes={
            "20519": "系统主商品ID与系统商品skuId必须二选一",
            "20520": "系统主商品ID传值不规范",
            "20521": "系统主商品ID最多支持20组",
            "20522": "系统商品skuId传值不规范",
            "20523": "系统商品skuId最多支持20组",
            "20525": "查询商品关联供应商有误",
        },
        formatter="format_generic_list",
        response_key="suppliers",
    ),
    # ── 写入操作 ──────────────────────────────────────
    "tag_add": ApiEntry(
        method="erp.item.tag.add",
        description="新增商品标签",
        param_map={"name": "name", "style": "styleType"},
        required_params=["name"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增商品标签「{name}」？",
    ),
    "tag_batch_update": ApiEntry(
        method="erp.item.tag.batch.update",
        description="设置商品标签",
        param_map={
            "tag_names": "tagNames",
            "tag_ids": "tagIds",
            "type": "operateType",
            "item_info_list": "itemInfoList",
        },
        required_params=["type", "item_info_list"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认批量设置商品标签？",
    ),
    "cat_add": ApiEntry(
        method="erp.item.seller.cat.add",
        description="新增商品分类",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "classify_add": ApiEntry(
        method="erp.item.classify.add",
        description="新增商品类目",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "brand_add": ApiEntry(
        method="item.brand.add",
        description="新增/修改商品品牌",
        param_map={"name": "brandName", "brand_id": "id"},
        required_params=["name"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增/修改品牌「{name}」？",
    ),
    "supplier_update": ApiEntry(
        method="erp.item.supplier.relevance",
        description="商品关联供应商信息更新",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "supplier_add": ApiEntry(
        method="erp.item.supplier.add",
        description="添加商品供应商关系",
        param_map={
            "item_id": "itemId",
            "outer_id": "outerId",
            "sku_outer_id": "skuOuterId",
            "sku_id": "skuId",
            "suppliers": "suppliers",
        },
        error_codes={
            "20501": "平台主商品ID与平台商家编码必须二选一",
            "20503": "供应商信息不能为空",
            "20504": "供应商信息不能超过1000组",
            "20516": "供应商信息有误",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "supplier_modify": ApiEntry(
        method="erp.item.supplier.update",
        description="修改商品供应商关系",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "supplier_delete": ApiEntry(
        method="erp.item.supplier.delete",
        description="删除商品供应商关系",
        param_map={
            "item_id": "itemId",
            "outer_id": "outerId",
            "supplier_ids": "supplierIds",
            "supplier_codes": "supplierCodes",
            "sku_outer_id": "skuOuterId",
            "sku_id": "skuId",
        },
        error_codes={
            "20501": "平台主商品ID与平台商家编码必须二选一",
            "20516": "供应商信息有误",
            "20517": "供应商ID至少要有一组",
            "20518": "供应商编码至少要有一组",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认删除商品供应商关系？",
    ),
    "product_add_update": ApiEntry(
        method="erp.item.general.addorupdate",
        description="修改/新增商品V2",
        error_codes={
            "20107": "查询商品SKU信息有误",
            "20113": "系统主商品ID信息不正确",
            "40002": "开始时间不能大于结束时间",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增/修改商品？",
    ),
    "product_add_update_simple": ApiEntry(
        method="item.general.addorupdate",
        description="修改/新增普通商品",
        param_map={
            "outer_id": "outerId",
            "title": "title",
            "item_id": "id",
            "skus": "skus",
            "short_title": "shortTitle",
            "barcode": "barcode",
            "purchase_price": "purchasePrice",
            "selling_price": "sellingPrice",
            "weight": "weight",
            "remark": "remark",
            "brand": "brand",
            "brand_id": "brandId",
            "cat_id": "catId",
            "seller_cids": "sellerCids",
            "active_status": "activeStatus",
            "unit": "unit",
            "make_gift": "makeGift",
            "unique_code_type": "uniqueCodeType",
        },
        required_params=["outer_id", "title"],
        error_codes={
            "20114": "系统主商品ID或平台商家编码不能为空",
            "20115": "平台商家编码不能超过64个字符",
            "20116": "商品标题不能为空",
            "20117": "商品标题不能超过128个字符",
            "20119": "SKU最多支持1000个",
            "20120": "平台规格商家编码不能为空",
            "20121": "平台规格商家编码不能超过64个字符",
            "20122": "平台规格商家编码重复",
            "20131": "SKU信息有误",
            "20143": "修改/新增普通商品有误",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "import_platform_item": ApiEntry(
        method="erp.tb.item.import",
        description="导入平台商品信息",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "update_history_price": ApiEntry(
        method="erp.item.history.price.update",
        description="更新商品历史成本价",
        param_map={
            "outer_id": "outerId",
            "item_id": "sysItemId",
            "sku_id": "sysSkuId",
            "price": "price",
            "date": "date",
        },
        required_params=["price"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "stock_update": ApiEntry(
        method="erp.item.available.stock.update",
        description="修改实际库存",
        param_map={
            "outer_ids": "outerIds",
            "sku_outer_ids": "skuOuterIds",
            "warehouse_id": "warehouseId",
            "stock_num": "stockNum",
            "over_stock_num": "overStockNum",
            "under_stock_num": "underStockNum",
        },
        required_params=["warehouse_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认修改实际库存？",
    ),
    "virtual_stock_update": ApiEntry(
        method="erp.item.virtual.stock.update",
        description="修改虚拟库存",
        param_map={
            "item_ids": "itemIds",
            "warehouse_id": "warehouseId",
            "stock_num": "stockNum",
            "sku_outer_ids": "skuOuterIds",
            "outer_ids": "outerIds",
        },
        required_params=["warehouse_id", "stock_num"],
        error_codes={
            "20112": "平台商家编码最多支持20组",
            "20305": "仓库ID不能为空或小于0",
            "20308": "商品信息不能为空",
            "20309": "平台规格商家编码最多支持20组",
            "20310": "虚拟库存数量不能为空或小于0",
            "20311": "平台商品信息最多支持20组",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认修改虚拟库存？",
    ),
    "virtual_stock_batch_update": ApiEntry(
        method="erp.item.virtual.stock.updateV2",
        description="批量修改虚拟库存",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "item_type_change": ApiEntry(
        method="erp.item.type.change",
        description="商品类型转换",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认转换商品类型？",
    ),
}
