"""
商品 API注册表

包含：商品查询/管理、SKU、标签、分类、品牌、供应商关系、库存 相关API
"""

from services.kuaimai.registry.base import ApiEntry

PRODUCT_REGISTRY = {
    # ── 商品查询 ──────────────────────────────────────
    "product_list": ApiEntry(
        method="item.list.query",
        description="查询商品列表",
        param_map={
            "status": "activeStatus",
            "start_date": "startModified",
            "end_date": "endModified",
            "item_type": "type",
            "order_by": "orderBy",
            "return_purchase": "whetherReturnPurchase",
        },
        formatter="format_product_list",
        response_key="items",
    ),
    "product_detail": ApiEntry(
        method="item.single.get",
        description="查询单个商品明细",
        param_map={
            "item_id": "sysItemId",
            "outer_id": "outerId",
            "return_purchase": "whetherReturnPurchase",
        },
        formatter="format_product_detail",
        response_key=None,
    ),
    "sku_info": ApiEntry(
        method="erp.item.single.sku.get",
        description="查询商品SKU信息",
        param_map={
            "sku_id": "sysSkuId",
            "sku_outer_id": "skuOuterId",
            "return_purchase": "whetherReturnPurchase",
        },
        formatter="format_sku_info",
        response_key=None,
    ),
    "sku_list": ApiEntry(
        method="erp.item.sku.list.get",
        description="查询商品SKU列表V2",
        param_map={
            "outer_id": "outerId",
            "item_id": "sysItemId",
            "return_purchase": "whetherReturnPurchase",
        },
        formatter="format_sku_info",
        response_key="itemSkus",
    ),
    "multi_product": ApiEntry(
        method="erp.item.list.get",
        description="查询多个商品信息V2",
        param_map={
            "outer_ids": "outerIds",
            "item_ids": "sysItemIds",
            "return_skus": "returnSkus",
        },
        defaults={"returnSkus": 1},
        formatter="format_product_list",
        response_key="items",
    ),
    "multicode_query": ApiEntry(
        method="erp.item.multicode.query",
        description="商品多码查询",
        param_map={
            "code": "code",
        },
        required_params=["code"],
        formatter="format_product_list",
        response_key="list",
    ),
    # ── 库存查询 ──────────────────────────────────────
    "stock_status": ApiEntry(
        method="stock.api.status.query",
        description="查询库存状态",
        param_map={
            "outer_id": "mainOuterId",
            "sku_outer_id": "skuOuterId",
            "warehouse_id": "warehouseId",
            "stock_statuses": "stockStatuses",
            "item_type": "itemType",
            "brand": "brands",
            "created": "created",
            "modified": "modified",
            "stock_start": "startStockModified",
            "stock_end": "endStockModified",
            "relation_fields": "relationInfoFields",
        },
        formatter="format_inventory_list",
        response_key="stockStatusVoList",
        page_size=50,
    ),
    "warehouse_stock": ApiEntry(
        method="erp.item.warehouse.list.get",
        description="查询仓库及商品库存信息",
        param_map={
            "outer_id": "outerId",
            "sku_outer_id": "skuOuterId",
        },
        formatter="format_warehouse_stock",
    ),
    "stock_in_out": ApiEntry(
        method="erp.item.stock.in.out.list",
        description="查询商品出入库记录",
        param_map={
            "outer_id": "outerId",
            "warehouse_id": "warehouseId",
            "start_date": "operateTimeBegin",
            "end_date": "operateTimeEnd",
            "order_type": "orderType",
            "order_number": "orderNumber",
        },
        formatter="format_stock_in_out",
    ),
    "virtual_warehouse": ApiEntry(
        method="erp.virtual.warehouse.query",
        description="查询虚拟仓",
        param_map={
            "name": "name",
        },
        formatter="format_generic_list",
        response_key="list",
    ),
    "history_cost_price": ApiEntry(
        method="erp.item.history.cost.price.query",
        description="商品历史成本价查询",
        param_map={
            "item_id": "sysItemId",
            "sku_id": "sysSkuId",
            "start_date": "startTime",
            "end_date": "endTime",
            "warehouse_ids": "warehouseIdList",
        },
        required_params=["item_id", "sku_id"],
        formatter="format_generic_list",
    ),
    # ── 标签/分类/品牌 查询 ────────────────────────────
    "tag_list": ApiEntry(
        method="erp.item.tag.list",
        description="查询商品标签",
        param_map={"name": "name"},
        formatter="format_tag_list",
    ),
    "cat_list": ApiEntry(
        method="erp.item.seller.cat.list.get",
        description="查询商品分类信息",
        formatter="format_generic_list",
        response_key="sellerCats",
    ),
    "classify_list": ApiEntry(
        method="item.classify.list.get",
        description="查询商品类目信息",
        formatter="format_generic_list",
        response_key="classifies",
    ),
    "brand_list": ApiEntry(
        method="brand.list.get",
        description="查询商品品牌信息",
        formatter="format_generic_list",
        response_key="items",
    ),
    # ── 对应关系/供应商 查询 ────────────────────────────
    "outer_id_list": ApiEntry(
        method="erp.item.outerid.list.get",
        description="商品对应关系查询",
        param_map={
            "outer_ids": "outerIds",
            "platform_ids": "numIidList",
            "shop_id": "userId",
            "taobao_id": "taobaoId",
        },
        formatter="format_generic_list",
        response_key="itemOuterIdInfos",
    ),
    "outer_id_by_item": ApiEntry(
        method="erp.item.outerid.list.byitem.get",
        description="商品对应关系查询(按商品ID)",
        param_map={
            "platform_ids": "numIidList",
            "shop_id": "userId",
            "taobao_id": "taobaoId",
        },
        required_params=["platform_ids"],
        formatter="format_generic_list",
        response_key="itemOuterIdInfos",
    ),
    "item_supplier_list": ApiEntry(
        method="erp.item.supplier.list.get",
        description="查询商品关联供应商信息",
        param_map={
            "item_ids": "sysItemIds",
            "sku_ids": "sysSkuIds",
            "outer_ids": "outerIds",
            "sku_outer_ids": "skuOuterIds",
        },
        formatter="format_generic_list",
        response_key="suppliers",
    ),
    # ── 写入操作 ──────────────────────────────────────
    "tag_add": ApiEntry(
        method="erp.item.tag.add",
        description="新增商品标签",
        param_map={"name": "name", "style": "styleType"},
        required_params=["name"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增商品标签「{name}」？",
    ),
    "tag_batch_update": ApiEntry(
        method="erp.item.tag.batch.update",
        description="设置商品标签",
        param_map={
            "tag_names": "tagNames",
            "tag_ids": "tagIds",
            "type": "operateType",
            "item_info_list": "itemInfoList",
        },
        required_params=["type", "item_info_list"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认批量设置商品标签？",
    ),
    "cat_add": ApiEntry(
        method="erp.item.seller.cat.add",
        description="新增商品分类",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "classify_add": ApiEntry(
        method="erp.item.classify.add",
        description="新增商品类目",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "brand_add": ApiEntry(
        method="item.brand.add",
        description="新增/修改商品品牌",
        param_map={"name": "brandName", "brand_id": "id"},
        required_params=["name"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增/修改品牌「{name}」？",
    ),
    "supplier_update": ApiEntry(
        method="erp.item.supplier.relevance",
        description="商品关联供应商信息更新",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "supplier_add": ApiEntry(
        method="erp.item.supplier.add",
        description="添加商品供应商关系",
        param_map={
            "item_id": "itemId",
            "outer_id": "outerId",
            "sku_outer_id": "skuOuterId",
            "sku_id": "skuId",
            "suppliers": "suppliers",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "supplier_modify": ApiEntry(
        method="erp.item.supplier.update",
        description="修改商品供应商关系",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "supplier_delete": ApiEntry(
        method="erp.item.supplier.delete",
        description="删除商品供应商关系",
        param_map={
            "item_id": "itemId",
            "outer_id": "outerId",
            "supplier_ids": "supplierIds",
            "supplier_codes": "supplierCodes",
            "sku_outer_id": "skuOuterId",
            "sku_id": "skuId",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认删除商品供应商关系？",
    ),
    "product_add_update": ApiEntry(
        method="erp.item.general.addorupdate",
        description="修改/新增商品V2",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增/修改商品？",
    ),
    "product_add_update_simple": ApiEntry(
        method="item.general.addorupdate",
        description="修改/新增普通商品",
        param_map={
            "outer_id": "outerId",
            "title": "title",
            "item_id": "id",
            "skus": "skus",
            "short_title": "shortTitle",
            "barcode": "barcode",
            "purchase_price": "purchasePrice",
            "selling_price": "sellingPrice",
            "weight": "weight",
            "remark": "remark",
            "brand": "brand",
            "brand_id": "brandId",
            "cat_id": "catId",
            "seller_cids": "sellerCids",
            "active_status": "activeStatus",
            "unit": "unit",
            "make_gift": "makeGift",
            "unique_code_type": "uniqueCodeType",
        },
        required_params=["outer_id", "title"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "import_platform_item": ApiEntry(
        method="erp.tb.item.import",
        description="导入平台商品信息",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "update_history_price": ApiEntry(
        method="erp.item.history.price.update",
        description="更新商品历史成本价",
        param_map={
            "outer_id": "outerId",
            "item_id": "sysItemId",
            "sku_id": "sysSkuId",
            "price": "price",
            "date": "date",
        },
        required_params=["price"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "stock_update": ApiEntry(
        method="erp.item.available.stock.update",
        description="修改实际库存",
        param_map={
            "outer_ids": "outerIds",
            "sku_outer_ids": "skuOuterIds",
            "warehouse_id": "warehouseId",
            "stock_num": "stockNum",
            "over_stock_num": "overStockNum",
            "under_stock_num": "underStockNum",
        },
        required_params=["warehouse_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认修改实际库存？",
    ),
    "virtual_stock_update": ApiEntry(
        method="erp.item.virtual.stock.update",
        description="修改虚拟库存",
        param_map={
            "item_ids": "itemIds",
            "warehouse_id": "warehouseId",
            "stock_num": "stockNum",
            "sku_outer_ids": "skuOuterIds",
            "outer_ids": "outerIds",
        },
        required_params=["warehouse_id", "stock_num"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认修改虚拟库存？",
    ),
    "virtual_stock_batch_update": ApiEntry(
        method="erp.item.virtual.stock.updateV2",
        description="批量修改虚拟库存",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "item_type_change": ApiEntry(
        method="erp.item.type.change",
        description="商品类型转换",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认转换商品类型？",
    ),
}
