"""
采购 API注册表

包含：供应商、采购单、收货单、采退单、上架单、采购建议 相关API
"""

from services.kuaimai.registry.base import ApiEntry

PURCHASE_REGISTRY = {
    # ── 供应商 查询 ───────────────────────────────────
    "supplier_list": ApiEntry(
        method="supplier.list.query",
        description="查询供应商列表（供应商基础信息）。按启用/停用状态筛选。查商品关联的供应商用item_supplier_list",
        param_map={
            "status": "status",
        },
        param_docs={
            "status": "供应商状态。可选值: 1=启用, 2=停用。示例: 1",
        },
        fetch_all=True,
        page_size=500,
        formatter="format_supplier_list",
    ),
    # ── 采购单 查询 ───────────────────────────────────
    "purchase_order_list": ApiEntry(
        method="purchase.order.query",
        description="查询采购单列表（向供应商下的采购订单）。按状态/单号/时间筛选。查三个月前的用purchase_order_history",
        param_map={
            "code": "code",
            "outer_code": "outerCode",
            "purchase_id": "id",
            "status": "status",
            "time_type": "timeType",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "code": "采购单号。示例: DB20260315001",
            "outer_code": "外部单据号（供应商系统）。示例: PO-2026-001",
            "purchase_id": "采购单ID。示例: 123456",
            "status": "采购单状态。可选值: WAIT_VERIFY(草稿), VERIFYING(待审核), GOODS_NOT_ARRIVED(未到货), FINISHED(已完成), CLOSE(已关闭)。多个逗号隔开。示例: GOODS_NOT_ARRIVED",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_purchase_order_list",
    ),
    "purchase_order_detail": ApiEntry(
        method="purchase.order.get",
        description="查询采购单完整详情（含采购商品明细/数量/价格/到货情况）。需要采购单ID（从purchase_order_list获取）",
        param_map={
            "purchase_id": "id",
            "pt_order_id": "ptOrderId",
        },
        param_docs={
            "purchase_id": "采购单ID（从purchase_order_list获取）。示例: 123456",
            "pt_order_id": "平台采购单ID。示例: 789012",
        },
        formatter="format_purchase_order_detail",
        response_key=None,
    ),
    # ── 采退单 查询 ───────────────────────────────────
    "purchase_return_list": ApiEntry(
        method="purchase.return.list.query",
        description="查询采购退货单列表（向供应商退货）。与售后退货不同，这是采购方向的退货",
        param_map={
            "status": "status",
            "code": "code",
            "outer_code": "outerCode",
            "time_type": "timeType",
            "tag_name": "tagName",
            "finance_status": "financeStatus",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "采退单状态。可选值: WAIT_OUT(待出库), PART_OUT(部分出库), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_OUT",
            "code": "采退单号。示例: DB20260315001",
            "outer_code": "外部单据号（供应商系统）。示例: PO-2026-001",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "tag_name": "标签名称（模糊搜索）。示例: 紧急",
            "finance_status": "财务状态。可选值: WAIT_PAY(待结算), PART_PAY(部分结算), FINISHED(已结算)。示例: WAIT_PAY",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_purchase_return_list",
    ),
    "purchase_return_detail": ApiEntry(
        method="purchase.return.list.get",
        description="查询采购退货单完整详情。需要采退单ID（从purchase_return_list获取）",
        param_map={"return_id": "id"},
        param_docs={
            "return_id": "采退单ID（必填，从purchase_return_list获取）。示例: 123456",
        },
        required_params=["return_id"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 收货单 查询 ───────────────────────────────────
    "warehouse_entry_list": ApiEntry(
        method="warehouse.entry.list.query",
        description="查询采购收货单列表（供应商送货到仓的收货记录）。按状态/单号/财务状态筛选",
        param_map={
            "status": "status",
            "code": "code",
            "outer_code": "outerCode",
            "finance_status": "financeStatus",
            "tag_name": "tagName",
            "flag": "flag",
            "prein_order_id": "preinOrderId",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "收货单状态。可选值: WAIT_IN(待收货), PART_IN(部分收货), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_IN",
            "code": "收货单号。示例: DB20260315001",
            "outer_code": "外部单据号（供应商系统）。示例: PO-2026-001",
            "finance_status": "财务状态。可选值: WAIT_PAY(待结算), PART_PAY(部分结算), FINISHED(已结算)。示例: WAIT_PAY",
            "tag_name": "标签名称（模糊搜索）。示例: 紧急",
            "flag": "标记。可选值: 0=未标记, 1=已标记。示例: 1",
            "prein_order_id": "预约入库单ID。示例: 123456",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_warehouse_entry_list",
    ),
    "warehouse_entry_detail": ApiEntry(
        method="warehouse.entry.list.get",
        description="查询收货单完整详情（收货商品/数量/差异）。需要收货单ID（从warehouse_entry_list获取）",
        param_map={"entry_id": "id"},
        param_docs={
            "entry_id": "收货单ID（必填，从warehouse_entry_list获取）。示例: 123456",
        },
        required_params=["entry_id"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 上架单 查询 ───────────────────────────────────
    "shelf_list": ApiEntry(
        method="erp.purchase.shelf.query",
        description="查询上架单列表（采购收货后的上架任务）。按状态/收货单号/时间筛选",
        param_map={
            "status": "status",
            "time_type": "timeType",
            "we_code": "weCode",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "上架单状态。可选值: WAIT_SHELF(待上架), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_SHELF",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "we_code": "收货单号（关联查询）。示例: DB20260315001",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_shelf_list",
    ),
    "shelf_detail": ApiEntry(
        method="erp.purchase.shelf.get",
        description="查询上架单完整详情（上架商品/数量/货位）。需要上架单ID（从shelf_list获取）",
        param_map={"shelf_id": "id"},
        param_docs={
            "shelf_id": "上架单ID（必填，从shelf_list获取）。示例: 123456",
        },
        required_params=["shelf_id"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 采购建议 ──────────────────────────────────────
    "purchase_strategy": ApiEntry(
        method="sale.purchase.strategy.query",
        description="查询采购建议（根据销售数据推荐补货商品和数量）。按商品名称或编码搜索。不是查采购单，查采购单用purchase_order_list",
        param_map={
            "query_key": "queryKey",
        },
        param_docs={
            "query_key": "查询关键字（必填）。按商品名称或商家编码搜索。示例: ABC123",
        },
        required_params=["query_key"],
        formatter="format_purchase_strategy",
        response_key="purchaseStrategyList",
    ),
    "purchase_strategy_calculate": ApiEntry(
        method="sale.purchase.strategy.calculate",
        description="触发采购建议计算任务（异步，用purchase_progress查进度）。计算完成后用purchase_strategy查看结果",
        param_map={
            "warehouse_code": "warehouseCode",
            "ignore_trade_out": "ignoreTradeOut",
            "ignore_refund": "ignoreRefund",
        },
        param_docs={
            "warehouse_code": "仓库编码（必填，通过warehouse_list获取）。示例: WH001",
            "ignore_trade_out": "是否忽略销售出库。可选值: true, false。默认false。示例: false",
            "ignore_refund": "是否忽略退货。可选值: true, false。默认false。示例: false",
        },
        required_params=["warehouse_code"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    "purchase_progress": ApiEntry(
        method="purchase.progress.query",
        description="查询采购建议计算进度（配合purchase_strategy_calculate使用）。不是查采购单进度",
        param_map={
            "progress_type": "progressType",
        },
        param_docs={
            "progress_type": "进度类型。可选值: 4=采购建议计算。默认4。示例: 4",
        },
        defaults={"progressType": 4},
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 收货 操作 ─────────────────────────────────────
    "warehouse_entry_receive": ApiEntry(
        method="warehouse.entry.receive",
        description="收货单收货",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "warehouse_entry_fast_receive": ApiEntry(
        method="warehouse.entry.fast.receive",
        description="采购快速收货",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "warehouse_entry_revert": ApiEntry(
        method="warehouse.entry.finished.revert",
        description="收货单打回",
        param_map={"entry_ids": "ids"},
        required_params=["entry_ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "shelf_save": ApiEntry(
        method="erp.purchase.shelf.save",
        description="上架单上架",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    # ── 归档 查询 ─────────────────────────────────────
    "purchase_order_history": ApiEntry(
        method="purchase.order.history.query",
        description="查询归档采购单（三个月前的历史采购单）。必须传起止日期。近期采购单用purchase_order_list",
        param_map={
            "code": "code",
            "purchase_id": "id",
            "status": "status",
            "time_type": "timeType",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "code": "采购单号。示例: DB20260315001",
            "purchase_id": "采购单ID。示例: 123456",
            "status": "采购单状态。可选值: WAIT_VERIFY(草稿), VERIFYING(待审核), GOODS_NOT_ARRIVED(未到货), FINISHED(已完成), CLOSE(已关闭)。示例: FINISHED",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "start_date": "起始日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        required_params=["start_date", "end_date"],
        formatter="format_purchase_order_list",
    ),
    "purchase_order_history_detail": ApiEntry(
        method="purchase.order.history.get",
        description="查询归档采购单完整详情。需要采购单ID（从purchase_order_history获取）",
        param_map={"purchase_id": "id"},
        param_docs={
            "purchase_id": "采购单ID（必填，从purchase_order_history获取）。示例: 123456",
        },
        required_params=["purchase_id"],
        formatter="format_purchase_order_detail",
        response_key=None,
    ),
    "warehouse_entry_history": ApiEntry(
        method="warehouse.entry.history.list.query",
        description="查询归档收货单列表（三个月前的历史收货单）。必须传起止日期",
        param_map={
            "code": "code",
            "status": "status",
            "time_type": "timeType",
            "finance_status": "financeStatus",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "code": "收货单号。示例: DB20260315001",
            "status": "收货单状态。可选值: WAIT_IN(待收货), PART_IN(部分收货), FINISHED(已完成), CLOSE(已关闭)。示例: FINISHED",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "finance_status": "财务状态。可选值: WAIT_PAY(待结算), PART_PAY(部分结算), FINISHED(已结算)。示例: FINISHED",
            "start_date": "起始日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        required_params=["start_date", "end_date"],
        formatter="format_warehouse_entry_list",
    ),
    "warehouse_entry_history_detail": ApiEntry(
        method="warehouse.entry.history.list.get",
        description="查询归档收货单完整详情。需要收货单ID（从warehouse_entry_history获取）",
        param_map={"entry_id": "id"},
        param_docs={
            "entry_id": "收货单ID（必填，从warehouse_entry_history获取）。示例: 123456",
        },
        required_params=["entry_id"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    "purchase_return_history": ApiEntry(
        method="purchase.return.history.list.query",
        description="查询归档采退单列表（三个月前的历史采购退货单）。必须传起止日期",
        param_map={
            "code": "code",
            "status": "status",
            "time_type": "timeType",
            "finance_status": "financeStatus",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "code": "采退单号。示例: DB20260315001",
            "status": "采退单状态。可选值: WAIT_OUT(待出库), PART_OUT(部分出库), FINISHED(已完成), CLOSE(已关闭)。示例: FINISHED",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "finance_status": "财务状态。可选值: WAIT_PAY(待结算), PART_PAY(部分结算), FINISHED(已结算)。示例: FINISHED",
            "start_date": "起始日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        required_params=["start_date", "end_date"],
        formatter="format_purchase_return_list",
    ),
    "purchase_return_history_detail": ApiEntry(
        method="purchase.return.history.list.get",
        description="查询归档采退单完整详情。需要采退单ID（从purchase_return_history获取）",
        param_map={"return_id": "id"},
        param_docs={
            "return_id": "采退单ID（必填，从purchase_return_history获取）。示例: 123456",
        },
        required_params=["return_id"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    "shelf_history": ApiEntry(
        method="erp.purchase.shelf.history.query",
        description="查询归档上架单列表（三个月前的历史上架单）。必须传起止日期",
        param_map={
            "status": "status",
            "time_type": "timeType",
            "we_code": "weCode",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "上架单状态。可选值: WAIT_SHELF(待上架), FINISHED(已完成), CLOSE(已关闭)。示例: FINISHED",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "we_code": "收货单号（关联查询）。示例: DB20260315001",
            "start_date": "起始日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期（必填）。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        required_params=["start_date", "end_date"],
        formatter="format_shelf_list",
    ),
    "shelf_history_detail": ApiEntry(
        method="erp.purchase.shelf.history.get",
        description="查询归档上架单完整详情。需要上架单ID（从shelf_history获取）",
        param_map={"shelf_id": "id"},
        param_docs={
            "shelf_id": "上架单ID（必填，从shelf_history获取）。示例: 123456",
        },
        required_params=["shelf_id"],
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 写入操作 ──────────────────────────────────────
    "supplier_add_update": ApiEntry(
        method="supplier.addorupdate",
        description="新建/修改供应商",
        param_map={
            "code": "code",
            "name": "name",
            "remark": "remark",
            "contact_name": "contactName",
            "mobile": "mobile",
            "phone": "phone",
            "email": "email",
            "address": "address",
            "category_name": "categoryName",
            "status": "status",
        },
        required_params=["code", "name"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新建/修改供应商？",
    ),
    "purchase_add": ApiEntry(
        method="purchase.add",
        description="新增采购单",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增采购单？",
    ),
    "purchase_add_update": ApiEntry(
        method="purchase.addorupdate",
        description="新建/修改采购单",
        param_map={
            "supplier_code": "supplierCode",
            "items": "items",
            "warehouse_code": "warehouseCode",
            "outer_code": "outerCode",
            "remark": "remark",
            "purchase_id": "id",
            "delivery_date": "deliveryDate",
            "status": "status",
            "pt_order_id": "ptOrderId",
            "template_name": "templateName",
            "express_no": "outSid",
        },
        required_params=["supplier_code", "items", "warehouse_code"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新建/修改采购单？",
    ),
    "purchase_status_update": ApiEntry(
        method="purchase.status.update",
        description="采购单状态更新",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "purchase_update_special": ApiEntry(
        method="purchase.update.ignore.status",
        description="更新采购单特殊字段",
        param_map={
            "purchase_id": "id",
            "outer_code": "outerCode",
            "template_name": "templateName",
            "express_no": "outSid",
            "supplier_code": "supplierCode",
        },
        required_params=["purchase_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "purchase_un_audit": ApiEntry(
        method="purchase.unAudit",
        description="采购单反审核",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认反审核采购单？",
    ),
    "purchase_return_save": ApiEntry(
        method="purchase.return.save",
        description="采退单保存",
        param_map={
            "supplier_code": "supplierCode",
            "items": "items",
            "warehouse_code": "warehouseCode",
            "outer_code": "prSourceId",
            "purchase_order_id": "purchaseOrderId",
            "return_id": "id",
            "remark": "remark",
        },
        required_params=["supplier_code", "items", "warehouse_code"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "purchase_return_out": ApiEntry(
        method="purchase.return.out",
        description="采退单出库",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "purchase_return_cancel": ApiEntry(
        method="purchase.return.cancel",
        description="采退单作废",
        param_map={"return_id": "id"},
        required_params=["return_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废采退单？此操作不可逆！",
    ),
    "warehouse_entry_add_update": ApiEntry(
        method="warehouse.entry.addorupdate",
        description="收货单新增/修改",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "warehouse_entry_cancel": ApiEntry(
        method="warehouse.entry.cancel",
        description="收货单作废",
        param_map={"entry_ids": "ids"},
        required_params=["entry_ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废收货单？此操作不可逆！",
    ),
    "pre_in_order_add": ApiEntry(
        method="purchase.pre.in.order.add",
        description="预约入库单新增",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "pre_in_order_update": ApiEntry(
        method="purchase.pre.in.order.update",
        description="预约入库单修改",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "pre_in_order_anti_audit": ApiEntry(
        method="purchase.pre.in.order.anti.audit",
        description="预约入库单反审核",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
}
