"""
交易 API注册表

包含：订单查询/管理、出库、物流、波次、唯一码 相关API
"""

from services.kuaimai.registry.base import ApiEntry

TRADE_REGISTRY = {
    # ── 订单查询 ──────────────────────────────────────
    "order_list": ApiEntry(
        method="erp.trade.list.query",
        description="查询订单列表（待付款/待审核/待财审/待打印/待包装/待称重/待发货/已发货/已完成/已关闭）。支持订单号/系统单号/买家/店铺/状态/时间等条件。返回订单头信息+商品明细+收货地址。⚠️不含淘宝和1688订单；拼多多不返回订单号(tid)和金额(payment)。需要拼多多完整数据请用outstock_order_query（仅含已发货或发货流程中的订单）；需要淘宝/1688请用outstock_query",
        param_map={
            "order_id": "tid",
            "system_id": "sid",
            "buyer": "buyerNick",
            "shop_ids": "userIds",
            "status": "status",
            "time_type": "timeType",
            "start_date": "startTime",
            "end_date": "endTime",
            "order_types": "types",
            "tag_ids": "tagIds",
            "except_ids": "exceptIds",
            "exception_status": "exceptionStatus",
            "only_contain": "onlyContain",
            "consigned_type": "consignedType",
            "express_nos": "outSids",
            "query_type": "queryType",
            "use_has_next": "useHasNext",
            "use_cursor": "useCursor",
            "cursor": "cursor",
        },
        param_docs={
            "order_id": "平台订单号（淘宝18位/抖音19位/京东16位/小红书P+18位/拼多多日期-数字串/1688为19位）。与system_id二选一。示例: 126036803257340376",
            "system_id": "ERP系统单号（16位纯数字，所有平台统一格式）。与order_id二选一。示例: 5759422420146938",
            "buyer": "买家昵称。示例: 张三",
            "shop_ids": "店铺ID（多个逗号隔开，通过shop_list获取）。示例: 12345,67890",
            "status": "订单状态（多个逗号隔开，不传=全部）。可选值: WAIT_BUYER_PAY(待付款), WAIT_AUDIT(待审核), WAIT_FINANCE_AUDIT(待财审), FINISHED_AUDIT(已审核), WAIT_EXPRESS_PRINT(待打印), WAIT_PACKAGE(待包装), WAIT_WEIGHT(待称重), WAIT_SEND_GOODS(待发货), WAIT_DEST_SEND_GOODS(待到货发货), SELLER_SEND_GOODS(已发货), FINISHED(已完成), CLOSED(已关闭)。示例: WAIT_AUDIT,WAIT_SEND_GOODS",
            "time_type": "时间类型（配合start_date/end_date使用）。可选值: created(下单时间), pay_time(付款时间), consign_time(发货时间), audit_time(审核时间), upd_time(修改时间)。不传默认按修改时间。示例: created",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "order_types": "订单类型（多个逗号隔开）。可选值: 0=普通, 1=货到付款, 3=平台, 4=线下, 6=预售, 7=合并, 8=拆分, 9=加急, 10=空包, 11=合单提示, 12=门店, 13=换货, 14=补发, 16=海外仓, 17=Lazada, 18=报损, 19=领用, 20=调整, 21=客户, 22=天猫直送, 23=平台预售, 24=京东直发, 25=京东供销, 33=分销, 34=供销, 35=京配, 36=平台分销, 50=天猫淘宝预售, 51=抖音厂商代发, 53=亚马逊FBA, 54=亚马逊FBM, 55=亚马逊多渠道, 56=奇门, 57=得物普通现货, 58=得物极速现货, 60=全款预售, 61=得物直发, 62=Lazada-FBL, 66=平台拆单, 99=出库单。示例: 0,7",
            "tag_ids": "标签ID（多个逗号隔开，通过tag_list获取）。示例: 101,102",
            "except_ids": "排除的标签ID（多个逗号隔开）。示例: 103",
            "exception_status": "系统异常标签ID（多个逗号隔开）。通过tag_list获取异常标签。示例: 201,202",
            "only_contain": "异常查询状态（不是商品编码过滤！）。可选值: 1=仅包含, 2=排除, 3=同时包含。配合exception_status使用。示例: 1",
            "consigned_type": "发货类型。可选值: 0=非ERP发货, 1=ERP发货。示例: 1",
            "express_nos": "快递单号（多个逗号隔开）。示例: SF1234567890",
            "query_type": "查询范围。可选值: 0=三个月内订单(默认), 1=归档订单(三个月前)。示例: 0",
            "use_has_next": "是否使用hasNext分页模式。可选值: true, false。大数据量时建议true。示例: true",
            "use_cursor": "是否使用游标分页。可选值: true, false。配合cursor使用。示例: true",
            "cursor": "分页游标。上一次查询返回的cursor值，用于翻页。示例: 1234567890",
        },
        error_codes={
            "20009": "系统订单号格式不正确",
        },
        param_hints={
            "order_id": "平台订单号（淘宝/抖音/京东等）。不确定是平台单号还是系统单号时优先用这个",
            "system_id": "ERP系统单号（16位数字）。用 order_id 查不到时改用这个",
        },
        retry_alt_params={
            "order_id": "system_id",
            "system_id": "order_id",
        },
        formatter="format_order_list",
    ),
    "order_log": ApiEntry(
        method="erp.trade.trace.list",
        description="查询订单操作日志（审核/验货/发货/拦截/修改等操作记录）。追溯订单处理过程用这个。不是查订单信息，查订单用order_list（⚠️只接受system_ids参数，需先从order_list获取system_id）",
        param_map={
            "system_ids": "sids",
            "operators": "operators",
            "action": "action",
            "content": "content",
            "start_time": "operateTimeStart",
            "end_time": "operateTimeEnd",
        },
        param_docs={
            "system_ids": "ERP系统单号（16位纯数字，多个逗号隔开，最多200组）。示例: 5759422420146938,5759422420146939",
            "operators": "操作人姓名（多个逗号隔开，最多20组）。示例: 张三,李四",
            "action": "操作动作。可选值: 审核, 验货, 发货, 拦截, 作废, 合并, 拆分, 修改 等。示例: 审核",
            "content": "日志内容关键字，模糊匹配。示例: 修改地址",
            "start_time": "操作起始时间。格式: YYYY-MM-DD（系统自动转换为时间戳）。示例: 2026-03-01",
            "end_time": "操作结束时间。格式: YYYY-MM-DD（系统自动转换为时间戳）。示例: 2026-03-15",
        },
        error_codes={
            "20001": "页码为空或不符合规定",
            "20002": "页数为空或不符合规定",
            "20009": "系统订单号格式不正确",
            "20020": "系统订单号数量最大支持200组",
            "20021": "操作人数量最大支持20组",
        },
        formatter="format_order_log",
    ),
    # ── 出库/物流 查询 ────────────────────────────────
    "outstock_query": ApiEntry(
        method="erp.trade.outstock.simple.query",
        description="查询订单列表-全平台全状态版（待付款/待审核/待财审/待打印/待包装/待称重/待发货/已发货/已完成/已关闭，对应ERP后台【交易→订单查询】）。覆盖全平台含全状态（含淘宝/1688/拼多多/抖音/京东/快手/小红书）。支持订单号/系统单号/买家/店铺/状态/时间等条件。返回订单头信息+商品明细+快递单号。⚠️拼多多不返回订单号(tid)和金额(payment)；需要拼多多完整数据请用outstock_order_query（仅含已发货或发货流程中的订单）",
        param_map={
            "order_id": "tid",
            "system_id": "sid",
            "buyer": "buyerNick",
            "shop_ids": "userIds",
            "status": "status",
            "time_type": "timeType",
            "start_date": "startTime",
            "end_date": "endTime",
            "express_no": "outSids",
            "express_nos": "outSids",
            "order_types": "types",
            "tag_ids": "tagIds",
            "except_ids": "exceptIds",
            "exception_status": "exceptionStatus",
            "only_contain": "onlyContain",
            "consigned_type": "consignedType",
            "query_type": "queryType",
            "use_has_next": "useHasNext",
            "use_cursor": "useCursor",
            "cursor": "cursor",
        },
        param_docs={
            "order_id": "平台订单号（淘宝18位/抖音19位/京东16位/小红书P+18位/拼多多日期-数字串/1688为19位）。与system_id二选一。示例: 126036803257340376",
            "system_id": "ERP系统单号（16位纯数字，所有平台统一格式）。与order_id二选一。示例: 5759422420146938",
            "buyer": "买家昵称。示例: 张三",
            "shop_ids": "店铺ID（多个逗号隔开，通过shop_list获取）。示例: 12345,67890",
            "status": "订单状态（多个逗号隔开，不传=全部）。可选值: WAIT_BUYER_PAY(待付款), WAIT_AUDIT(待审核), WAIT_FINANCE_AUDIT(待财审), FINISHED_AUDIT(已审核), WAIT_EXPRESS_PRINT(待打印), WAIT_PACKAGE(待包装), WAIT_WEIGHT(待称重), WAIT_SEND_GOODS(待发货), WAIT_DEST_SEND_GOODS(待到货发货), SELLER_SEND_GOODS(已发货), FINISHED(已完成), CLOSED(已关闭)。示例: SELLER_SEND_GOODS",
            "time_type": "时间类型（配合start_date/end_date使用）。可选值: created(下单时间), pay_time(付款时间), consign_time(发货时间), audit_time(审核时间), upd_time(修改时间)。不传默认按修改时间。示例: consign_time",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "express_no": "快递单号（单个或多个逗号隔开）。与express_nos功能相同。示例: SF1234567890",
            "express_nos": "快递单号（多个逗号隔开）。与express_no功能相同。示例: SF1234567890,YT9876543210",
            "order_types": "订单类型（多个逗号隔开）。可选值: 0=普通, 1=货到付款, 3=平台, 4=线下, 6=预售, 7=合并, 8=拆分, 9=加急, 10=空包, 11=合单提示, 12=门店, 13=换货, 14=补发, 16=海外仓, 17=Lazada, 18=报损, 19=领用, 20=调整, 21=客户, 22=天猫直送, 23=平台预售, 24=京东直发, 25=京东供销, 33=分销, 34=供销, 35=京配, 36=平台分销, 50=天猫淘宝预售, 51=抖音厂商代发, 53=亚马逊FBA, 54=亚马逊FBM, 55=亚马逊多渠道, 56=奇门, 57=得物普通现货, 58=得物极速现货, 60=全款预售, 61=得物直发, 62=Lazada-FBL, 66=平台拆单, 99=出库单。示例: 0,7",
            "tag_ids": "标签ID（多个逗号隔开，通过tag_list获取）。示例: 101,102",
            "except_ids": "排除的标签ID（多个逗号隔开）。示例: 103",
            "exception_status": "系统异常标签ID（多个逗号隔开）。通过tag_list获取异常标签。示例: 201,202",
            "only_contain": "异常查询状态（不是商品编码过滤！）。可选值: 1=仅包含, 2=排除, 3=同时包含。配合exception_status使用。示例: 1",
            "consigned_type": "发货类型。可选值: 0=非ERP发货, 1=ERP发货。示例: 1",
            "query_type": "查询范围。可选值: 0=三个月内订单(默认), 1=归档订单(三个月前)。示例: 0",
            "use_has_next": "是否使用hasNext分页模式。可选值: true, false。大数据量时建议true。示例: true",
            "use_cursor": "是否使用游标分页。可选值: true, false。配合cursor使用。示例: true",
            "cursor": "分页游标。上一次查询返回的cursor值，用于翻页。示例: 1234567890",
        },
        param_hints={
            "order_id": "平台订单号。不确定是平台单号还是系统单号时优先用这个",
            "system_id": "ERP系统单号（16位数字）。用 order_id 查不到时改用这个",
        },
        retry_alt_params={
            "order_id": "system_id",
            "system_id": "order_id",
        },
        formatter="format_shipment_list",
    ),
    "express_query": ApiEntry(
        method="erp.trade.multi.packs.query",
        description="查询订单的包裹和快递信息（一单多包裹场景）。用系统单号sid或快递单号查。不含物流轨迹",
        param_map={
            "system_id": "sid",
            "express_no": "outSid",
        },
        param_docs={
            "system_id": "ERP系统单号（16位纯数字，所有平台统一格式）。示例: 5759422420146938",
            "express_no": "快递单号。示例: SF1234567890",
        },
        response_key=None,
        formatter="format_express_list",
    ),
    "outstock_order_query": ApiEntry(
        method="erp.wave.logistics.order.query",
        description="销售出库单查询（仅含已发货或发货流程中的订单，对应ERP后台【仓储→波次→销售出库单】）。所有平台均返回完整订单号(tid)和金额(payment/payAmount)，包括拼多多。支持系统单号/平台单号/物流单号/店铺/时间等条件。返回订单头+商品出库明细+快递信息。⚠️待审核/待付款等未进入发货流程的订单查不到；不含淘宝和1688",
        param_map={
            "order_id": "tids",
            "system_id": "sids",
            "shop_ids": "userIds",
            "status_list": "statusList",
            "time_type": "timeType",
            "start_date": "timeBegin",
            "end_date": "timeEnd",
            "express_nos": "outSids",
            "wave_ids": "waveIds",
            "short_ids": "shortIds",
        },
        param_docs={
            "order_id": "平台订单号（淘宝18位/抖音19位/京东16位/小红书P+18位/拼多多日期-数字串/1688为19位）。多个逗号隔开。与system_id二选一。示例: 126036803257340376",
            "system_id": "ERP系统单号（16位纯数字，多个逗号隔开）。与order_id二选一。示例: 5759422420146938",
            "shop_ids": "店铺ID（多个逗号隔开，通过shop_list获取）。示例: 12345,67890",
            "status_list": "出库单状态列表（多个逗号隔开）。可选值: 10=待处理, 20=预处理完成, 30=发货中, 50=已发货, 70=已关闭, 90=已作废。示例: 50",
            "time_type": "时间类型（整数）。可选值: 1=创建时间, 2=发货时间, 3=付款时间, 4=下单时间, 5=承诺时间, 6=打印时间。示例: 1",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "express_nos": "快递单号（多个逗号隔开）。示例: SF1234567890,YT9876543210",
            "wave_ids": "波次ID（多个逗号隔开）。示例: 10001,10002",
            "short_ids": "拣货单短ID（多个逗号隔开）。示例: S001,S002",
        },
        error_codes={
            "9": "业务逻辑错误",
            "32": "未设置单号时timeType/timeBegin/timeEnd参数必填",
            "33": "参数超限（pageSize≤200, 各ID≤50个）",
            "400": "资源异常",
        },
        param_hints={
            "order_id": "平台订单号。不确定是平台单号还是系统单号时优先用这个",
            "system_id": "ERP系统单号（16位数字）。用 order_id 查不到时改用这个",
        },
        retry_alt_params={
            "order_id": "system_id",
            "system_id": "order_id",
        },
        formatter="format_outstock_order_list",
    ),
    # ── 波次 查询 ─────────────────────────────────────
    "wave_query": ApiEntry(
        method="erp.trade.waves.query",
        description="查询波次信息（批量拣货任务）。波次是仓库批量处理订单的单位。查单个订单物流不用这个",
        param_map={
            "start_date": "start",
            "end_date": "end",
            "pick_start": "pickStartTime",
            "pick_end": "pickEndTime",
            "status": "status",
        },
        param_docs={
            "start_date": "波次创建起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "波次创建结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "pick_start": "拣货起始时间。格式: YYYY-MM-DD。示例: 2026-03-01",
            "pick_end": "拣货结束时间。格式: YYYY-MM-DD。示例: 2026-03-15",
            "status": "波次状态。可选值: 1=进行中, 3=已完成, 4=已取消。示例: 1",
        },
        formatter="format_generic_list",
    ),
    "wave_sorting_query": ApiEntry(
        method="erp.trade.wave.sorting.query",
        description="查询波次内的分拣明细（各订单分配到哪个格口）。必须先有波次ID，通过wave_query获取",
        param_map={
            "wave_id": "waveId",
        },
        param_docs={
            "wave_id": "波次ID（必填）。通过wave_query获取。示例: 10001",
        },
        required_params=["wave_id"],
        formatter="format_generic_list",
    ),
    # ── 唯一码 查询 ───────────────────────────────────
    "unique_code_query": ApiEntry(
        method="erp.item.unique.code.query",
        description="查询唯一码信息（SN码/IMEI/自定义码）。用于序列号管理的商品追踪。普通商品不用这个",
        param_map={
            "code": "uniqueCodes",
            "system_ids": "sids",
            "code_type": "codeType",
            "type": "type",
            "start_date": "updateStart",
            "end_date": "updateEnd",
            "consign_start": "consignStart",
            "consign_end": "consignEnd",
            "short_ids": "shortIds",
            "after_sale_codes": "afterSaleOrderCodes",
            "wave_id": "waveId",
            "receive_start": "receiveTimeStart",
            "receive_end": "receiveTimeEnd",
            "create_start": "createStart",
            "create_end": "createEnd",
            "no_need_total": "noNeedTotal",
        },
        param_docs={
            "code": "唯一码（多个逗号隔开）。示例: UC001,UC002",
            "system_ids": "ERP系统单号（16位纯数字，多个逗号隔开）。示例: 5759422420146938,5759422420146939",
            "code_type": "唯一码类型。可选值: 1(SN码), 2(IMEI), 3(自定义码)。示例: 1",
            "type": "查询类型。可选值: 0(全部), 1(已入库), 2(已出库), 3(已退货)。示例: 0",
            "start_date": "更新起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "更新结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "consign_start": "发货起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "consign_end": "发货结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "short_ids": "拣货单短ID（多个逗号隔开）。示例: S001,S002",
            "after_sale_codes": "售后单号（多个逗号隔开）。示例: AS001,AS002",
            "wave_id": "波次ID。通过wave_query获取。示例: 10001",
            "receive_start": "收货起始时间。格式: YYYY-MM-DD。示例: 2026-03-01",
            "receive_end": "收货结束时间。格式: YYYY-MM-DD。示例: 2026-03-15",
            "create_start": "创建起始时间。格式: YYYY-MM-DD。示例: 2026-03-01",
            "create_end": "创建结束时间。格式: YYYY-MM-DD。示例: 2026-03-15",
            "no_need_total": "是否不需要总数统计。可选值: true, false。大数据量时传true可提升性能。示例: true",
        },
        formatter="format_generic_list",
    ),
    # ── 物流 查询 ─────────────────────────────────────
    "logistics_company_list": ApiEntry(
        method="erp.trade.logistics.company.user.list",
        description="查询已配置的物流公司列表（可按仓库筛选）。查看有哪些快递公司可选。不是查快递单号",
        param_map={
            "warehouse_id": "warehouseId",
        },
        param_docs={
            "warehouse_id": "仓库ID（通过warehouse_list获取）。不传则返回所有仓库的物流公司。示例: 1001",
        },
        fetch_all=True,
        page_size=500,
        formatter="format_logistics_company",
    ),
    "logistics_template_list": ApiEntry(
        method="erp.trade.logistics.template.user.list",
        description="查询仓库的物流模板列表（面单模板配置）。必须传仓库ID。不是查快递单号",
        param_map={
            "warehouse_id": "warehouseId",
        },
        param_docs={
            "warehouse_id": "仓库ID（必填，通过warehouse_list获取）。示例: 1001",
        },
        required_params=["warehouse_id"],
        formatter="format_generic_list",
    ),
    "waybill_get": ApiEntry(
        method="erp.trade.waybill.code.get",
        description="根据系统单号获取已分配的物流单号（快递单号）。仅返回单号，不含物流轨迹。查包裹详情用express_query",
        param_map={
            "system_ids": "sids",
        },
        param_docs={
            "system_ids": "ERP系统单号（16位纯数字，多个逗号隔开）。示例: 5759422420146938,5759422420146939",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    "upload_memo_flag": ApiEntry(
        method="erp.trade.upload.memo.flag",
        description="上传订单备注和旗帜到平台（同步到淘宝等平台显示）。需要订单号+店铺ID+备注+旗帜全部必填",
        param_map={
            "order_id": "tid",
            "memo": "memo",
            "flag": "flag",
            "shop_id": "userId",
        },
        param_docs={
            "order_id": "平台订单号（淘宝18位/抖音19位/京东16位/小红书P+18位/拼多多日期-数字串/1688为19位）。必填。示例: 126036803257340376",
            "memo": "备注内容。必填。示例: 客户要求周末配送",
            "flag": "旗帜颜色。必填。可选值: 0(无), 1(红), 2(黄), 3(绿), 4(蓝), 5(紫)。示例: 1",
            "shop_id": "店铺ID（必填，通过shop_list获取）。示例: 12345",
        },
        required_params=["order_id", "memo", "flag", "shop_id"],
        error_codes={
            "50": "旗帜类型不合法（0灰/1红/2橙/3绿/4蓝/5紫）",
            "30009": "上传备注与旗帜缺少必要参数",
            "30010": "上传备注与旗帜失败",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 写入操作 ──────────────────────────────────────
    "order_create": ApiEntry(
        method="erp.trade.create",
        description="创建系统手工单",
        param_map={
            "shop_id": "userId",
            "warehouse_id": "warehouseId",
            "orders": "orders",
            "payment": "payment",
            "order_id": "tid",
            "receiver_name": "receiverName",
            "receiver_state": "receiverState",
            "receiver_city": "receiverCity",
            "receiver_district": "receiverDistrict",
            "receiver_street": "receiverStreet",
            "receiver_address": "receiverAddress",
            "receiver_mobile": "receiverMobile",
            "receiver_phone": "receiverPhone",
            "receiver_zip": "receiverZip",
            "post_fee": "postFee",
            "buyer": "buyerNick",
            "seller_memo": "sellerMemo",
            "express_code": "expressCode",
            "force": "force",
        },
        required_params=["shop_id", "warehouse_id", "orders", "payment",
                         "receiver_name", "receiver_state", "receiver_city",
                         "receiver_district", "receiver_street", "receiver_address"],
        error_codes={
            "50": "订单类型值不合法",
            "30051": "店铺编号不能为空",
            "30052": "订单商品明细集合不能为空",
            "30053": "收件人姓名不能为空",
            "30055": "收件省份不能为空",
            "30056": "收件市不能为空",
            "30057": "收件详细地址不能为空",
            "30058": "收件区县不能为空",
            "30059": "实付金额不能为空",
            "30060": "邮费不能为空",
            "30061": "orders参数传入有误，解析失败",
            "30069": "商品销售价格式错误",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认创建系统手工单？",
    ),
    "order_create_new": ApiEntry(
        method="erp.trade.create.new",
        description="创建自建平台订单",
        error_codes={
            "50": "平台状态枚举值不合法",
            "30051": "店铺编号不能为空",
            "30052": "订单商品明细集合不能为空",
            "30053": "收件人姓名不能为空",
            "30059": "实付金额不能为空",
            "30060": "邮费不能为空",
            "30065": "收件人手机号不能为空",
            "30066": "收件人手机号格式有误",
            "30067": "商家编码不能为空",
            "30068": "商品销售价不能为空",
            "30069": "商品销售价格式错误",
            "30072": "平台编号不能为空",
            "30073": "平台状态不能为空",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认创建自建平台订单？",
    ),
    "receiver_update": ApiEntry(
        method="erp.trade.receiver.info.update",
        description="修改订单收货地址",
        param_map={
            "order_id": "tid",
            "system_id": "sid",
            "receiver_name": "receiverName",
            "receiver_state": "receiverState",
            "receiver_city": "receiverCity",
            "receiver_district": "receiverDistrict",
            "receiver_address": "receiverAddress",
            "receiver_mobile": "receiverMobile",
            "receiver_phone": "receiverPhone",
            "receiver_zip": "receiverZip",
        },
        required_params=["receiver_name", "receiver_state", "receiver_city",
                         "receiver_district", "receiver_address"],
        error_codes={
            "9": "业务异常",
            "33": "详细收货地址字符长度不能超过228个",
            "50": "收件详细地址不能为空",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认修改订单收货地址？",
    ),
    "seller_memo_update": ApiEntry(
        method="erp.trade.seller.memo.upload",
        description="修改订单卖家备注与旗帜",
        param_map={
            "order_id": "tid",
            "system_id": "sid",
            "seller_memo": "sellerMemo",
            "flag": "flag",
        },
        error_codes={
            "50": "卖家备注与旗帜二选一必填",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "tag_batch_update": ApiEntry(
        method="erp.trade.tag.batch.update",
        description="批量修改订单标签",
        param_map={
            "order_ids": "tids",
            "system_ids": "sids",
            "tag_ids": "tagIds",
            "type": "type",
        },
        required_params=["tag_ids", "type"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "order_cancel": ApiEntry(
        method="erp.trade.cancel",
        description="订单作废",
        param_map={
            "order_ids": "tids",
            "system_ids": "sids",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废订单？此操作不可逆！",
    ),
    "order_intercept": ApiEntry(
        method="erp.trade.send.goods.intercept",
        description="订单发货拦截",
        param_map={
            "system_ids": "sids",
        },
        error_codes={
            "30003": "系统订单号不能为空",
            "30004": "系统订单号格式不正确",
            "30005": "系统订单号最多支持20组",
            "30006": "订单发货拦截失败",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认拦截订单的发货？",
    ),
    "trade_consign": ApiEntry(
        method="erp.trade.consign",
        description="上传发货",
        param_map={
            "system_ids": "sids",
            "consign_type": "consignType",
            "express_code": "expressCode",
            "express_no": "outSid",
            "operate_type": "operateType",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认上传发货信息？",
    ),
    "trade_pack": ApiEntry(
        method="erp.trade.pack",
        description="包装验货",
        param_map={
            "system_id": "sid",
            "unique_codes": "uniqueCodes",
            "can_force": "canForce",
            "express_no": "outSid",
            "order_scan_infos": "orderScanInfos",
        },
        required_params=["can_force"],
        error_codes={
            "30000": "扫描数量不规范，不能小于0",
            "30001": "扫码类型不规范",
            "30002": "包装验货失败",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "wave_pick_hand": ApiEntry(
        method="erp.trade.wave.pick.hand",
        description="波次手动拣选",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "unique_code_receive": ApiEntry(
        method="erp.trade.unique.code.receive",
        description="订单唯一码收货",
        param_map={"unique_code": "uniqueCode"},
        required_params=["unique_code"],
        error_codes={
            "30007": "唯一码号不能为空",
            "30008": "订单唯一码收货失败",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "wave_seed": ApiEntry(
        method="erp.trade.wave.seed",
        description="波次播种回传",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "unique_code_generate": ApiEntry(
        method="erp.item.unique.code.generate",
        description="新增商品唯一码",
        param_map={"generate_params": "generateParams"},
        required_params=["generate_params"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "unique_code_validate": ApiEntry(
        method="erp.wave.unique.code.validate",
        description="校验波次唯一码",
        param_map={
            "unique_codes": "uniqueCodes",
            "start_time": "startTime",
            "end_time": "endTime",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "unique_code_update": ApiEntry(
        method="erp.item.unique.code.update",
        description="商品唯一码更新",
        param_map={"generate_params": "generateParams"},
        required_params=["generate_params"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "change_warehouse": ApiEntry(
        method="erp.trade.change.warehouse",
        description="修改订单仓库",
        param_map={
            "system_ids": "sids",
            "warehouse_id": "warehouseId",
            "force": "force",
        },
        required_params=["system_ids", "warehouse_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认修改订单仓库？",
    ),
    "logistics_template_update": ApiEntry(
        method="erp.trade.logistics.template.update",
        description="更新订单物流模板",
        param_map={
            "system_ids": "sids",
            "logistics_company_id": "logisticsCompanyId",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "fast_stock_update": ApiEntry(
        method="erp.fast.stock.update",
        description="即入即出匹配",
        param_map={
            "outer_id": "outerId",
            "num": "num",
            "type": "type",
            "need_goods_section": "needGoodsSection",
            "warehouse_code": "warehouseCode",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "order_remark_update": ApiEntry(
        method="erp.trade.order.remark.update",
        description="修改订单商品备注",
        param_map={
            "order_id": "orderId",
            "remark": "remark",
        },
        required_params=["order_id", "remark"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "order_remark_batch_update": ApiEntry(
        method="erp.trade.order.remark.batchUpdate",
        description="批量修改订单商品备注",
        param_map={
            "system_id": "sid",
            "order_id": "tid",
            "orders": "orders",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "trade_halt": ApiEntry(
        method="erp.trade.halt",
        description="订单挂起",
        param_map={
            "order_ids": "tids",
            "system_ids": "sids",
            "auto_unhalt": "autoUnHalt",
            "unhalt_type": "unHaltType",
            "halt_time_unit": "haltTimeUnit",
            "halt_time_val": "haltTimeVal",
            "is_urgent": "isUrgent",
        },
        required_params=["auto_unhalt"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认挂起订单？",
    ),
    "trade_unhalt": ApiEntry(
        method="erp.trade.unhalt",
        description="订单解挂",
        param_map={
            "order_ids": "tids",
            "system_ids": "sids",
        },
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
}
