"""
仓储 API注册表

包含：调拨、入出库、盘点、下架、货位、加工单、批次库存 相关API
"""

from services.kuaimai.registry.base import ApiEntry

WAREHOUSE_REGISTRY = {
    # ── 调拨 查询 ─────────────────────────────────────
    "allocate_list": ApiEntry(
        method="erp.allocate.task.query",
        description="查询调拨单列表（仓库间商品转移）。按状态/单号/时间筛选。查调拨明细用allocate_detail",
        param_map={
            "status": "status",
            "code": "code",
            "start_date": "startModified",
            "end_date": "endModified",
            "label_name": "labelName",
        },
        param_docs={
            "status": "调拨单状态。可选值: WAIT_OUT(待出库), PART_OUT(部分出库), WAIT_IN(待入库), PART_IN(部分入库), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_OUT",
            "code": "调拨单号。示例: DB20260315001",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "label_name": "标签名称（模糊搜索）。示例: 紧急",
        },
        formatter="format_allocate_list",
    ),
    "allocate_detail": ApiEntry(
        method="erp.allocate.task.detail.query",
        description="查询调拨单的商品明细（调拨了哪些商品/数量）。查调拨单列表用allocate_list",
        param_map={
            "code": "code",
            "start_date": "startModified",
            "end_date": "endModified",
            "label_name": "labelName",
        },
        param_docs={
            "code": "调拨单号。示例: DB20260315001",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "label_name": "标签名称（模糊搜索）。示例: 紧急",
        },
        formatter="format_allocate_detail",
        response_key=None,
    ),
    "allocate_in_list": ApiEntry(
        method="allocate.in.task.query",
        description="查询调拨入库单列表（目标仓收货维度）。与allocate_list的区别：这个侧重入库端的收货状态",
        param_map={
            "status": "status",
            "code": "code",
            "custom_type": "customType",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "调拨入库单状态。可选值: WAIT_IN(待入库), PART_IN(部分入库), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_IN",
            "code": "调拨入库单号。示例: DB20260315001",
            "custom_type": "自定义类型编码。示例: 1",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_other_in_out_list",
    ),
    "allocate_in_detail": ApiEntry(
        method="allocate.in.task.get",
        description="查询调拨入库单的商品收货明细。需要调拨入库单ID（从allocate_in_list获取）",
        param_map={"allocate_id": "id"},
        param_docs={
            "allocate_id": "调拨入库单ID（从allocate_in_list获取）。示例: 123456",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    "allocate_out_list": ApiEntry(
        method="allocate.out.task.query",
        description="查询调拨出库单列表（源仓出库维度）。与allocate_list的区别：这个侧重出库端的发货状态",
        param_map={
            "status": "status",
            "code": "code",
            "time_type": "timeType",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "调拨出库单状态。可选值: WAIT_OUT(待出库), PART_OUT(部分出库), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_OUT",
            "code": "调拨出库单号。示例: DB20260315001",
            "time_type": "时间类型。可选值: create(创建时间), modified(修改时间)。默认modified。示例: modified",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_other_in_out_list",
    ),
    "allocate_out_detail": ApiEntry(
        method="allocate.out.task.get",
        description="查询调拨出库单的商品出库明细。需要调拨出库单ID（从allocate_out_list获取）",
        param_map={"allocate_id": "id"},
        param_docs={
            "allocate_id": "调拨出库单ID（从allocate_out_list获取）。示例: 123456",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 其他入出库 查询 ────────────────────────────────
    "other_in_list": ApiEntry(
        method="other.in.order.query",
        description="查询其他入库单列表（非采购/非调拨的入库，如盘盈入库）。采购入库查warehouse_entry_list",
        param_map={
            "status": "status",
            "code": "code",
            "outer_code": "outerCode",
            "custom_type": "customTypeStr",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "入库单状态。可选值: WAIT_IN(待入库), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_IN",
            "code": "入库单号。示例: DB20260315001",
            "outer_code": "外部单据号（供应商系统）。示例: PO-2026-001",
            "custom_type": "自定义类型编码（字符串）。示例: 1",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_other_in_out_list",
    ),
    "other_in_detail": ApiEntry(
        method="other.in.order.get",
        description="查询其他入库单的商品明细。需要入库单ID（从other_in_list获取）",
        param_map={"order_id": "id"},
        param_docs={
            "order_id": "入库单ID（从other_in_list获取）。示例: 123456",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    "other_out_list": ApiEntry(
        method="other.out.order.query",
        description="查询其他出库单列表（非销售/非调拨的出库，如报损出库）。销售出库查outstock_query",
        param_map={
            "status": "status",
            "code": "code",
            "outer_code": "outerCode",
            "custom_type": "customTypeStr",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "出库单状态。可选值: WAIT_OUT(待出库), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_OUT",
            "code": "出库单号。示例: DB20260315001",
            "outer_code": "外部单据号（供应商系统）。示例: PO-2026-001",
            "custom_type": "自定义类型编码（字符串）。示例: 1",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_other_in_out_list",
    ),
    "other_out_detail": ApiEntry(
        method="other.out.order.get",
        description="查询其他出库单的商品明细。需要出库单ID（从other_out_list获取）",
        param_map={"order_id": "id"},
        param_docs={
            "order_id": "出库单ID（从other_out_list获取）。示例: 123456",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 盘点 查询 ─────────────────────────────────────
    "inventory_sheet_list": ApiEntry(
        method="inventory.sheet.query",
        description="查询盘点单列表（库存盘点任务）。按状态/单号/时间筛选。查盘点明细用inventory_sheet_detail",
        param_map={
            "status": "status",
            "code": "code",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "status": "盘点单状态。可选值: WAIT_CHECK(待盘点), CHECKING(盘点中), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_CHECK",
            "code": "盘点单号。示例: DB20260315001",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_inventory_sheet_list",
    ),
    "inventory_sheet_detail": ApiEntry(
        method="inventory.sheet.get",
        description="查询盘点单的商品盘点明细（盘点数量/差异）。必须传盘点单号",
        param_map={
            "code": "code",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "code": "盘点单号（必填）。示例: DB20260315001",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        required_params=["code"],
        formatter="format_inventory_sheet_detail",
        response_key=None,
    ),
    # ── 下架 查询 ─────────────────────────────────────
    "unshelve_list": ApiEntry(
        method="erp.wms.unshelve.order.query",
        description="查询下架单列表（货位商品下架任务）。仓库管理场景使用",
        param_map={
            "code": "code",
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "code": "下架单号。示例: DB20260315001",
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_unshelve_list",
    ),
    "unshelve_detail": ApiEntry(
        method="erp.wms.unshelve.order.get",
        description="查询下架单的商品明细。需要下架单ID（从unshelve_list获取）",
        param_map={"unshelve_id": "id"},
        param_docs={
            "unshelve_id": "下架单ID（从unshelve_list获取）。示例: 123456",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 货位/库存 查询 ────────────────────────────────
    "goods_section_list": ApiEntry(
        method="asso.goods.section.sku.query",
        description="查询货位库存列表（商品在仓库货架的具体位置和数量）。精细化仓库管理场景使用",
        param_map={
            "start_date": "startModified",
            "end_date": "endModified",
        },
        param_docs={
            "start_date": "起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_goods_section_list",
    ),
    "batch_stock_list": ApiEntry(
        method="erp.wms.product.stock.query",
        description="查询商品批次效期库存（保质期管理场景，如食品/化妆品）。必须传店铺ID。查普通库存用stock_status",
        param_map={
            "sku_ids": "skuIds",
            "num_iids": "numIids",
            "tids": "tids",
            "shop_id": "userId",
        },
        param_docs={
            "sku_ids": "SKU ID（多个逗号隔开）。示例: 10001,10002",
            "num_iids": "平台商品数字ID（多个逗号隔开）。示例: 88001,88002",
            "tids": "平台订单号（多个逗号隔开）。示例: 126036803257340376",
            "shop_id": "店铺ID（必填，通过shop_list获取）。示例: 12345",
        },
        required_params=["shop_id"],
        formatter="format_batch_stock_list",
    ),
    # ── 加工单 查询 ───────────────────────────────────
    "process_order_list": ApiEntry(
        method="erp.stock.product.order.query",
        description="查询加工单列表（组装/拆卸任务）。商品组合加工场景使用。不是查商品信息",
        param_map={
            "status": "status",
            "code": "code",
            "type": "type",
            "start_date": "modifiedStart",
            "end_date": "modifiedEnd",
            "product_start": "productTimeStart",
            "product_end": "productTimeEnd",
            "finished_start": "finishedTimeStart",
            "finished_end": "finishedTimeEnd",
            "created_start": "createdStart",
            "created_end": "createdEnd",
        },
        param_docs={
            "status": "加工单状态。可选值: WAIT_PRODUCT(待加工), PRODUCTING(加工中), FINISHED(已完成), CLOSE(已关闭)。示例: WAIT_PRODUCT",
            "code": "加工单号。示例: DB20260315001",
            "type": "加工类型。可选值: 1=组装, 2=拆卸。示例: 1",
            "start_date": "修改起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "修改结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "product_start": "加工起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "product_end": "加工结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "finished_start": "完成起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "finished_end": "完成结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
            "created_start": "创建起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "created_end": "创建结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_process_order_list",
    ),
    "process_order_detail": ApiEntry(
        method="erp.stock.product.order.get",
        description="查询加工单的商品加工明细（原料/成品/数量）。需要加工单ID（从process_order_list获取）",
        param_map={"product_order_id": "productOrderId"},
        param_docs={
            "product_order_id": "加工单ID（从process_order_list获取）。示例: 123456",
        },
        formatter="format_generic_detail",
        response_key=None,
    ),
    # ── 货位进出记录 ──────────────────────────────────
    "section_record_list": ApiEntry(
        method="goods.section.in.out.record.query",
        description="查询货位进出记录（商品上架/下架/移位的流水日志）。按单据号或操作时间查询",
        param_map={
            "order_number": "orderNumber",
            "start_date": "operateStartTime",
            "end_date": "operateEndTime",
        },
        param_docs={
            "order_number": "关联单据号。示例: DB20260315001",
            "start_date": "操作起始日期。格式: YYYY-MM-DD。示例: 2026-03-01",
            "end_date": "操作结束日期。格式: YYYY-MM-DD。示例: 2026-03-15",
        },
        formatter="format_section_record_list",
    ),
    # ── 写入操作 ──────────────────────────────────────
    "allocate_add": ApiEntry(
        method="allocate.task.add",
        description="新增完成的调拨单",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增调拨单？",
    ),
    "allocate_create": ApiEntry(
        method="allocate.task.status.create",
        description="新增调拨单",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增调拨单？",
    ),
    "allocate_in_receive": ApiEntry(
        method="allocate.in.task.receive",
        description="调拨入库单收货",
        param_map={
            "allocate_id": "id",
            "receive_details": "receiveDetails",
            "outer_code": "weSourceId",
        },
        required_params=["allocate_id", "receive_details"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "allocate_out_direct": ApiEntry(
        method="erp.allocate.out.task.out",
        description="调拨出库单直接出库",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "other_in_add": ApiEntry(
        method="other.in.order.add",
        description="新增其他入库单",
        param_map={
            "items": "items",
            "warehouse_code": "warehouseCode",
            "outer_code": "weSourceId",
            "custom_type": "customType",
            "remark": "remark",
            "status": "status",
            "code": "code",
            "in_location": "inLocation",
        },
        required_params=["items", "warehouse_code"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增其他入库单？",
    ),
    "other_in_cancel": ApiEntry(
        method="erp.other.in.order.cancel",
        description="作废其他入库单",
        param_map={"ids": "ids"},
        required_params=["ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废其他入库单？此操作不可逆！",
    ),
    "other_out_add": ApiEntry(
        method="other.out.order.add",
        description="新增其他出库单",
        param_map={
            "items": "items",
            "warehouse_code": "warehouseCode",
            "custom_type": "customType",
            "outer_code": "prSourceId",
            "remark": "remark",
            "status": "status",
            "out_location": "outLocation",
        },
        required_params=["items", "warehouse_code"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认新增其他出库单？",
    ),
    "other_out_cancel": ApiEntry(
        method="erp.other.out.order.cancel",
        description="作废其他出库单",
        param_map={"ids": "ids"},
        required_params=["ids"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
        confirm_template="确认作废其他出库单？此操作不可逆！",
    ),
    "inventory_batch_update": ApiEntry(
        method="inventory.sheet.batch.update",
        description="盘点单库存盘点",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "unshelve_save": ApiEntry(
        method="erp.wms.unshelve.order.save",
        description="新建/修改下架单",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "unshelve_execute": ApiEntry(
        method="erp.wms.unshelve.order.unshelve",
        description="下架单下架",
        param_map={"unshelve_id": "id"},
        required_params=["unshelve_id"],
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
    "goods_section_delete": ApiEntry(
        method="asso.goods.section.sku.del.query",
        description="查询货位库存已删除数据列表（历史记录）。这是查询接口，不是删除操作",
        response_key=None,
        formatter="format_generic_detail",
    ),
    "upshelf_batch": ApiEntry(
        method="erp.wms.upshelf.batch",
        description="暂存区批量上架",
        is_write=True,
        response_key=None,
        formatter="format_generic_detail",
    ),
}
