-- 145 rollback：仅允许在新应用启用前删除空的资产本体和来源关联。
DO $rollback$
BEGIN
    IF EXISTS (SELECT 1 FROM user_asset_refs LIMIT 1)
       OR EXISTS (SELECT 1 FROM user_assets LIMIT 1)
    THEN
        RAISE EXCEPTION 'USER_ASSETS_NOT_EMPTY';
    END IF;
END
$rollback$;

DROP FUNCTION IF EXISTS register_user_asset(
    UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT,
    TEXT, BIGINT, TEXT, JSONB, TEXT, UUID, TEXT, TEXT, TEXT, UUID,
    UUID, UUID, UUID, UUID, INTEGER, TEXT, TEXT, JSONB, TIMESTAMPTZ
);
DROP FUNCTION IF EXISTS _bind_user_asset_ref(
    UUID, TEXT, UUID, UUID, TEXT, TEXT, TEXT, UUID, UUID, UUID, UUID,
    UUID, INTEGER, TEXT, TEXT, JSONB, TIMESTAMPTZ
);
DROP FUNCTION IF EXISTS _resolve_user_asset(
    UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT,
    TEXT, BIGINT, TEXT, JSONB, TIMESTAMPTZ
);
DROP TABLE IF EXISTS user_asset_refs;
DROP TABLE IF EXISTS user_assets;
