SET LOCAL ROLE everydayai_owner;
DO $$
BEGIN
 IF EXISTS (SELECT 1 FROM agent_runtime_catalog_facts WHERE catalog_document::TEXT LIKE '%runtime_read%')
    OR EXISTS (SELECT 1 FROM agent_runtime_effective_toolset_facts WHERE toolset_document::TEXT LIKE '%runtime_read%') THEN
   RAISE EXCEPTION 'AR225_ROLLBACK_BLOCKED_BY_EFFECTIVE_TOOLSET';
 END IF;
END $$;
DROP FUNCTION read_agent_runtime_conversation(UUID,UUID,UUID,TEXT,TEXT,INTEGER,INTEGER);
DROP FUNCTION read_agent_runtime_knowledge(UUID,UUID,UUID,TEXT,TEXT,INTEGER,TEXT,INTEGER);
DROP FUNCTION read_agent_runtime_evidence(UUID,UUID,UUID,TEXT,TEXT,INTEGER,TEXT,TEXT,TEXT,TEXT,INTEGER);
DROP FUNCTION read_agent_runtime_memory(UUID,UUID,UUID,TEXT,TEXT,INTEGER,TEXT,UUID,TEXT,INTEGER);
DROP FUNCTION read_agent_runtime_artifact(UUID,UUID,UUID,TEXT,TEXT,INTEGER,TEXT,TEXT,TEXT,INTEGER,INTEGER,INTEGER);
DROP FUNCTION read_agent_runtime_erp(UUID,UUID,UUID,TEXT,TEXT,INTEGER,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,BOOLEAN,TEXT,INTEGER);
DROP FUNCTION _agent_runtime_read_context(UUID,UUID,UUID,TEXT,TEXT,INTEGER);
RESET ROLE;
