SET LOCAL ROLE everydayai_owner;
DROP FUNCTION IF EXISTS record_agent_action_cost_strict(UUID,UUID,TEXT,SMALLINT,SMALLINT,TEXT,TEXT,TEXT);
DROP FUNCTION IF EXISTS record_agent_action_cost_strict(UUID,UUID,TEXT,INTEGER,INTEGER,TEXT,TEXT,TEXT);
RESET ROLE;
