SET LOCAL ROLE everydayai_owner;
REVOKE ALL ON FUNCTION record_agent_sync_phase_v3(UUID,UUID,UUID,BIGINT,TIMESTAMPTZ,TEXT,TEXT,JSONB,JSONB) FROM everydayai_agent_runtime_worker;
DROP FUNCTION record_agent_sync_phase_v3(UUID,UUID,UUID,BIGINT,TIMESTAMPTZ,TEXT,TEXT,JSONB,JSONB);
RESET ROLE;
