SET LOCAL ROLE everydayai_owner;
DROP FUNCTION IF EXISTS runtime_submit_ingress_v6_required(
 UUID,UUID,UUID,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,
 TEXT,JSONB,JSONB,TEXT,JSONB,UUID,TEXT,UUID,UUID,UUID,TEXT);
RESET ROLE;
