SET LOCAL ROLE everydayai_owner;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tasks WHERE delivery_context @> '{"runtime":true}'::JSONB)
       OR EXISTS (SELECT 1 FROM agent_runtime_sessions)
       OR EXISTS (SELECT 1 FROM agent_session_commands) THEN
        RAISE EXCEPTION 'AR_17_4_ROLLBACK_BLOCKED_OWNER_TRANSITIONS' USING ERRCODE = '55000';
    END IF;
END $$;
REVOKE EXECUTE ON FUNCTION restore_prepared_task_to_legacy_actor(UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,TEXT,TEXT,TEXT),
 mark_prepared_task_runtime_owned(UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,TEXT,TEXT,TEXT,UUID,UUID),
 runtime_submit_ingress_v5_owner_transition(UUID,UUID,UUID,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,JSONB,JSONB,TEXT,JSONB,UUID,TEXT,UUID,UUID,UUID,TEXT)
 FROM everydayai_runtime,everydayai_wecom_runtime;
REVOKE EXECUTE ON FUNCTION enqueue_wecom_runtime_turn_v6(JSONB,UUID,UUID,UUID,JSONB,JSONB,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT)
 FROM everydayai_wecom_runtime;
DROP FUNCTION enqueue_wecom_runtime_turn_v6(JSONB,UUID,UUID,UUID,JSONB,JSONB,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT);
DROP FUNCTION runtime_submit_ingress_v5_owner_transition(UUID,UUID,UUID,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,JSONB,JSONB,TEXT,JSONB,UUID,TEXT,UUID,UUID,UUID,TEXT);
DROP FUNCTION mark_prepared_task_runtime_owned(UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,TEXT,TEXT,TEXT,UUID,UUID);
DROP FUNCTION restore_prepared_task_to_legacy_actor(UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,TEXT,TEXT,TEXT);
DROP FUNCTION _agent_runtime_validate_task_binding(UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,TEXT,TEXT,TEXT);
RESET ROLE;
