"""Agent Runtime 应用层稳定 SPI。"""

from services.agent.runtime.ports.action_repository import (
    ActionMutationOutcome,
    ActionMutationReceipt,
    ActionRepositoryPort,
    ChatActionSubmissionPort,
)
from services.agent.runtime.ports.event import RuntimeEventPort
from services.agent.runtime.ports.executor import (
    ExecutionOutcome,
    ExecutionReceipt,
    ExecutorPort,
)
from services.agent.runtime.ports.model import (
    ModelCallError,
    ModelCallUnknownError,
    ModelExecutionBinding,
    ModelInputReceipt,
    ModelOutput,
    ModelOutputKind,
    ModelPort,
    ModelProviderError,
    ModelRequestOptions,
    ModelResponseStartObserver,
    ModelResponseStreamObserver,
    ModelResponseReceipt,
    ModelStreamDelta,
    ModelStepRequest,
    ModelStepResult,
    ModelToolCall,
    ModelUsage,
    ProviderAttemptOutcome,
    ProviderAttemptReceipt,
)
from services.agent.runtime.ports.model_attempt import (
    ModelAttemptOutcome,
    ModelAttemptReceipt,
    ModelAttemptRepositoryPort,
    ModelAttemptSnapshot,
)
from services.agent.runtime.ports.projection import (
    ProjectionClaim,
    ProjectionOutcome,
    ProjectionOutboxPort,
    ProjectionPort,
    ProjectionReceipt,
)
from services.agent.runtime.ports.projection_recovery import (
    ProjectionDeadRecoveryPort,
    ProjectionDeadRecoveryReceipt,
)
from services.agent.runtime.ports.repository import (
    ClaimOutcome,
    MutationOutcome,
    MutationReceipt,
    RunClaim,
    RuntimeRepositoryPort,
    SessionSnapshot,
)
from services.agent.runtime.ports.sandbox_job import (
    SandboxJobOutcome,
    SandboxJobReceipt,
    SandboxJobRepositoryPort,
)

__all__ = [
    "ActionMutationOutcome",
    "ActionMutationReceipt",
    "ActionRepositoryPort",
    "ChatActionSubmissionPort",
    "ExecutionOutcome",
    "ExecutionReceipt",
    "ExecutorPort",
    "ModelCallError",
    "ModelCallUnknownError",
    "ModelExecutionBinding",
    "ModelInputReceipt",
    "ModelOutput",
    "ModelOutputKind",
    "ModelPort",
    "ModelProviderError",
    "ModelRequestOptions",
    "ModelResponseStartObserver",
    "ModelResponseStreamObserver",
    "ModelResponseReceipt",
    "ModelStreamDelta",
    "ModelStepRequest",
    "ModelStepResult",
    "ModelToolCall",
    "ModelUsage",
    "ProviderAttemptOutcome",
    "ProviderAttemptReceipt",
    "ModelAttemptOutcome",
    "ModelAttemptReceipt",
    "ModelAttemptRepositoryPort",
    "ModelAttemptSnapshot",
    "ProjectionOutcome",
    "ProjectionClaim",
    "ProjectionOutboxPort",
    "ProjectionPort",
    "ProjectionReceipt",
    "ProjectionDeadRecoveryPort",
    "ProjectionDeadRecoveryReceipt",
    "RuntimeEventPort",
    "RuntimeRepositoryPort",
    "ClaimOutcome",
    "MutationOutcome",
    "MutationReceipt",
    "RunClaim",
    "SandboxJobOutcome",
    "SandboxJobReceipt",
    "SandboxJobRepositoryPort",
    "SessionSnapshot",
]
